### ISSUE TITLE
new Hue device_tracker creates entity with same id as iCloud device_tracker

### ISSUE THREAD

**Issue by Mariusthvdb** [robmarkcole/Hue-sensors-HASS#100]
HI, as mentioned in https://github.com/robmarkcole/Hue-sensors-HASS/issues/99#issuecomment-450756410
this seems ground for confusion. Ive tried to adapt the new hue.py device_tracker as follows:

```
        kwargs = dict(
            dev_id= "hue_" + slugify(sensor.name),
            host_name= "hue_" + sensor.name,
            attributes={
                "last_updated": dt_util.as_local(dt_util.parse_datetime(last_updated)),
                "unique_id": sensor.uniqueid,
            },
        )
```

but am not sure this is the correct way of creating the dev_id in particular. It does work:

![schermafbeelding 2019-01-02 om 00 49 47](https://user-images.githubusercontent.com/33354141/50577467-d239e100-0e28-11e9-8d65-c172be9a76c8.jpg)

tried to make it show as Hue Telefoon somehow, but didn't yet succeed doing so..

**Comment by yottatsa** [comment]
Host name could have spaces, so just fix it with `host_name="Hue " + ...`. BTW I think it’s better to have the same name, because no device trackers has a "namespace"-prefix. You could always override the name afterwards.

**Comment by Mariusthvdb** [comment]
because no device trackers has a "namespace"-prefix

This is not the case, please see @pnbruckner Life360 device_tracker as example. Works very nicely indeed and immediate identification of the platform that made the decice_tracker.life360_name.

**Comment by Mariusthvdb** [comment]
since the device_tracker is now created with the prefix hue_ (as per request above, thanks!) this can be closed. Thank you @yottatsa
