### ISSUE TITLE
Motion icon turning to yellow

### ISSUE THREAD

**Issue by WhistleMaster** [robmarkcole/Hue-sensors-HASS#103]
Hi !

Great work on that custom sensor ! One request I would have is that the motion icon turn to yellow when a motion is detected and back to blue.

Would it be possible to implement that ?

Thanks !

**Comment by yottatsa** [comment]
Yes, but it requires converting the sensor to a binary.

**Comment by WhistleMaster** [comment]
Thanks for the answer. I see the rational behind #54. I will use "customizer" in the mean time to change the icon and the color.

**Comment by scaarup** [comment]
I made that here: https://github.com/scaarup/Hue-sensors-HASS/blob/master/custom_components/binary_sensor/hue.py

**Comment by yottatsa** [comment]
Yep, should be working this way.
<img width="299" alt="screenshot 2019-01-06 at 19 41 29" src="https://user-images.githubusercontent.com/68171/50740770-44287680-11eb-11e9-989b-7c459e9b5e8b.png">
