### ISSUE TITLE
Update 0.86.2

### ISSUE THREAD

**Issue by thykor** [robmarkcole/Hue-sensors-HASS#109]
please note with updating to 0.86.2, HA will fail

**Comment by Ener-G** [comment]
0.86.3 is working?

**Comment by raoulteeuwen** [comment]
> please note with updating to 0.86.2, HA will fail

Can you supply some more info on your setup, any errors, how does it break? I don't have a problem wit 0.86.1, .2 and .3

**Comment by thykor** [comment]
Sorry guys, I went into it for a while, apparently I missed something myself.
