### ISSUE TITLE
It's a error?

### ISSUE THREAD

**Issue by anarro** [robmarkcole/Hue-sensors-HASS#11]
Hi,

I have this error in Logs file,

> 2017-11-02` 15:14:45 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform hue
> Traceback (most recent call last):
>   File "/usr/src/app/homeassistant/helpers/entity_component.py", line 170, in _async_setup_platform
>     SLOW_SETUP_MAX_WAIT, loop=self.hass.loop)
>   File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
>     return fut.result()
>   File "/usr/local/lib/python3.6/asyncio/futures.py", line 245, in result
>     raise self._exception
>   File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/sensor/hue.py", line 24, in setup_platform
>     import hue_sensors as hs
> ModuleNotFoundError: No module named 'hue_sensors'
> 

I have copy your files in my "./custom_components/" folder..
After restart HA I can see a new folder named "./deps/..." and inside I have some new files and folders and a file named "./hue_sensors.py" with another files... it's correct?

Thank you,

**Comment by robmarkcole** [comment]
Hi, this isn’t a code error, rather an error in your config or you have some old files floating around. 
Cheers

**Comment by anarro** [comment]
Hi Robin,
Thank you for your fast answer.

We use the last version of HA (56.2), and after the reboot the I think that the component work good.. but own HA need this folders and files (./deps/...).. 

Tthanks you,
Antoni

**Comment by phillprice** [comment]
I have a fresh Hassio install and I too get the same problem where I assume there must be an automated attempt to install the python dependancy for hue-sensors from another repo but its not doing so?

**Comment by robmarkcole** [comment]
Hi Phil, could be a Hassio specific issue which I am unsure how to debug. Are there any similar issues on the Hassio repo?

**Comment by rogersmj** [comment]
I am having the same problem using this on my Hassio install (currently 0.57.3). The phue.conf is in the main config directory, as expected. This is the first time I'm using a custom component with Hassio, and I haven't run into any dependency issues like this before.

```
File "/config/custom_components/sensor/hue.py", line 24, in setup_platform
    import hue_sensors as hs
ModuleNotFoundError: No module named 'hue_sensors'
```
All I have done is put the files in config/custom_components, as the instructions said, and added:

```
- platform: hue
```
to my `sensor:` section.

I am unsure how to proceed. If anyone has any recommendations on how to debug I would welcome them.

**Comment by robmarkcole** [comment]
@rogersmj glad that fixes it. I will soon start work on a new Hue compoent using the phue library as requested by HA core team, so will not be making any further changes to this component.
