### ISSUE TITLE
Question: How can I get the device tracker to pick up my wifes iphone?

### ISSUE THREAD

**Issue by imbaimbaimba** [robmarkcole/Hue-sensors-HASS#116]
Hi everyone,

These sensors pick up my phone nicely, but only that. She has the exact same setup as me in the Hue app. Any instructions on how to make it find her phone?

**Comment by yottatsa** [comment]
Check that on Routines -> Home and Away you have Location aware enabled. It will appear once the phone reports the location, which is usually happens when it crosses the Geofence.
