### ISSUE TITLE
Morton sensors no longer visible

### ISSUE THREAD

**Issue by kirbyschapman** [robmarkcole/Hue-sensors-HASS#124]
Just upgraded to hass 0.89.1. Downloaded the latest versions of sensor.py and binary_sensor.py. pt them in the sub hue_custom. The singer switched work fine, but I can no longer see the hue motion sensors. Thoughts?

**Comment by raoulteeuwen** [comment]
Check http://<HA ip addresss>:8123/dev-state to check for new names of the motion sensors. Are there binary_sensor.XXX 's? Look in your configuration.yaml for the name you previously gave the sensors, like maybe with "motion" in them? Are they still sensor.XXX in for instance your templates? Change the main sensor in binary_sensor.

**Comment by WiReCoder** [comment]
@kirbyschapman HI, I had the same problem and after inspecting the new code I found the part of code for the Motion sensor (SML) was missing, after adding this to my sensor.py it worked properly again.
I'm not familiar yet with contributing to Github,  So below the two parts I added.

There are two parts of code, in the "parse_hue_api_response" routing the SML "elif modelid == 'SML':" is missing
`            elif modelid == 'SML':
                if _key not in data_dict.keys():
                    data_dict[_key] = parse_sml(sensor)
                else:
                    data_dict[_key].update(parse_sml(sensor))
`

And the "pars_sml" routine itself was missing also:

`def parse_sml(response):
    """Parse the json for a SML Hue motion sensor and return the data."""
    if response['type'] == "ZLLLightLevel":
        lightlevel = response['state']['lightlevel']
        if lightlevel is not None:
            lx = round(float(10**((lightlevel-1)/10000)), 2)
            dark = response['state']['dark']
            daylight = response['state']['daylight']
            data = {'light_level': lightlevel,
                    'lx': lx,
                    'dark': dark,
                    'daylight': daylight, }
        else:
            data = {'light_level': 'No light level data'}

    elif response['type'] == "ZLLTemperature":
        if response['state']['temperature'] is not None:
            data = {'temperature': response['state']['temperature']/100.0}
        else:
            data = {'temperature': 'No temperature data'}

    elif response['type'] == "ZLLPresence":
        name_raw = response['name']
        arr = name_raw.split()
        arr.insert(-1, 'motion')
        name = ' '.join(arr)
        hue_state = response['state']['presence']
        if hue_state is True:
            state = 'on'
        else:
            state = 'off'

        data = {'model': 'SML',
                'name': name,
                'state': state,
                'battery': response['config']['battery'],
                'on': response['config']['on'],
                'reachable': response['config']['reachable'],
                'last_updated': response['state']['lastupdated'].split('T')}
    return data
`

HTH...

**Comment by robmarkcole** [comment]
Been quiet for a while, closing
