### ISSUE TITLE
Correct names in custom_updater

### ISSUE THREAD

**Issue by MightyMilster** [robmarkcole/Hue-sensors-HASS#129]
Thank you for updating `custom_updater.json` so that it points to the correct location now!!!

By no means a big issue but shouldn't the file  have...
device_tracker.**huesensor**
binary_sensor.**huesensor**
sensor.**huesensor**
Rather than .hue ?

**Comment by nin9s** [comment]
regarding `custom_updater.json` - shouldnt "local_location" be like:

    `  "local_location" : `"/custom_components/hue_custom/device_tracker.py",`
rather then

     ` "local_location" : "/custom_components/huesensor/device_tracker.py",`

**Comment by MightyMilster** [comment]
Hi. I'm not sure why you would think that. As part of the great migration custom components had to alter their architecture to comply withe latest releases of HA. Rob with input from users decided on the folder name "huesensor".  You could put in a differently named folder if you like. But if you are using custom_updater, any new releases will be installed to "huesensor" not "hue_custom"

**Comment by nin9s** [comment]
Thanks @mightymister to be honest I thought it to be the other way around especially as the sensors refused to be detected by hassio if I were using huesensors 

What am I missing?

**Comment by MightyMilster** [comment]
Are you declaring 
- platform: huesensor
In your config? Under the 3 different domains?

**Comment by nin9s** [comment]
that did the trick. Had some historical references to hue_custom .
Thanks for pointing me in the right direction!

**Comment by robmarkcole** [comment]
Been quiet for a while, closing
