### ISSUE TITLE
Future request: add friends of hue lights

### ISSUE THREAD

**Issue by warcanoid** [robmarkcole/Hue-sensors-HASS#131]
I want to open future request for friends of hue lights: https://www.mueller-licht.de/produktserien/tint/, they are very cheap and popular in europe.
So the problem is the light are flickering time to time, and someone has managed to stop this, on this post: https://github.com/home-assistant/home-assistant/issues/20638.
Please implement this.
The lights also flickering when you call service light.turn_on or homeassistant.tunr_on, but this is solved with call service: hue.hue_activate_scene.

**Comment by robmarkcole** [comment]
OK this should be a feature request on home-assistant, as this component doesn't deal with lights, just sensors/switches. Sorry I should have understood that.
