### ISSUE TITLE
Hue Bridge firmware update breaks connection

### ISSUE THREAD

**Issue by wallywalts** [robmarkcole/Hue-sensors-HASS#133]
Just updated the firmware on the hue bridge v2 (April 2 1931069120) which seems to have broken the sensor link to hassio. Lights can still be controlled, sensors have all but disappeared. 

One of the lines in the new firmware looks like the culprit:

-for better security we slightly changed the way apps connect to you hue bridge

Any clues?

**Comment by claytonjn** [comment]
My instinct is that something else is going on. My bridge is BSB002 | 1931140060 | 4/2/19 (I'm in the Hue beta program) and it's been working fine.

**Comment by wallywalts** [comment]
Ok that’s good to know. It’s quite possible it’s due to my hassio version. I’m still on 0.81 as I’ve been reluctant to upgrade due to relative stability. I guess now I have no choice! Will try to upgrade later and report back.

**Comment by glassbase** [comment]
It may have something to do with the PR https://github.com/home-assistant/home-assistant/pull/22598 if you’re running HA beta (you didn’t mention)

**Comment by wallywalts** [comment]
I managed to get it going again, after upgrading I needed to reconfigure as per the front page. I see it changed quite a bit in the last 6 months. Bit of a pain as I had everything setup nicely but happy to have it working again.
