### ISSUE TITLE
error in 0.92 - Integration huesensor not found when trying to verify its sensor platform.

### ISSUE THREAD

**Issue by h4nc** [robmarkcole/Hue-sensors-HASS#135]
coming from here
https://github.com/robmarkcole/Hue-sensors-HASS/issues/122#issuecomment-486542790

I get the following errors when I run the check tool (Check Home Assistant configuration):

```
General Errors: 
    - Integration ambilights not found when trying to verify its light platform.
    - Integration huesensor not found when trying to verify its sensor platform.
    - Component not found: hue
    - Integration ambihue not found when trying to verify its switch platform.
```

So are we running in new troubles when we update to 0.92?

@robmarkcole

**Comment by robmarkcole** [comment]
I [think](https://developers.home-assistant.io/blog/2019/04/12/new-integration-structure.html) we need to add an `init` file, and manifest?

**Comment by h4nc** [comment]
Thanks for the quick fix. The error about huesensor is gone now.

But there is still this one:

` - Component not found: hue`

I don't have another custom component hue. I use the component hue but it's not custom.

**Comment by robmarkcole** [comment]
OK great

Your other issue is not related to this custom component, probably a config error, cheers

**Comment by quentinsf** [comment]
Hi Rob - I have a feeling that it's meant to have a manifest.json file too, now; something like:

```
{
        "domain": "huesensor",
        "name": "Hue sensor custom component",
        "documentation": "https://github.com/robmarkcole/Hue-sensors-HASS",
        "requirements": [],
        "dependencies": [],
        "codeowners": ["@robmarkcole"]
}
```

Apologies for not doing checking thoroughly and doing a PR - I'm supposed to be at work :-)

**Comment by robmarkcole** [comment]
Docs state `manifest.json` is optional for custom components, but no harm to add

**Comment by sfgabe** [comment]
I can confirm it needs the above as manifest.json to work in 0.92

**Comment by pmatias** [comment]
Adding the manifest file solved the issue for me :)

**Comment by robmarkcole** [comment]
@quentinsf thanks for the info, added in https://github.com/robmarkcole/Hue-sensors-HASS/releases/tag/1.4
