### ISSUE TITLE
Update custom_updater.json

### ISSUE THREAD

**Issue by lucacri** [robmarkcole/Hue-sensors-HASS#139]
Hi!
The `custom_updater.json` is still stuck at version 1.0.5 . Could you update it to 1.4 (and latest)?

**Comment by robmarkcole** [comment]
Please submit a PR
thanks

**Comment by lucacri** [comment]
Well I can, but in general that file should be updated once there is a new release so everyone can automatically update from HA :-)

**Comment by robmarkcole** [comment]
Someone else added this and now isn't providing ongoing updates, welcome to OSS :-)

**Comment by warcanoid** [comment]
Custom updater showing update from 1.0.5 to 1.4, wont update, I see also that cc files are all having 1.0.5 version, so how to get 1.4?
