### ISSUE TITLE
Custom Updater showing old version even though latest installed.

### ISSUE THREAD

**Issue by aptonline** [robmarkcole/Hue-sensors-HASS#141]
I have the latest version installed but custom updater shows an older version, if I try and update using the UI it does nothing.

![Screenshot 2019-05-25 at 10 28 22](https://user-images.githubusercontent.com/190136/58367503-0ac18080-7ed8-11e9-8382-116d5b8c9d5e.png)

**Comment by Ahmed-BRN** [comment]
Same here, deleted and re added all but no change.

**Comment by Cyr-ius** [comment]
Normal, the version in the files remained in 1.0.5
sensor.py , binary_sensor.py and device_tracker.py
`__version__ = "1.0.5"`

**Comment by aegjoyce** [comment]
Yup, if you want a quick fix edit the file to __version__ = "1.4". May break future updates though.

**Comment by h4nc** [comment]
Same here

**Comment by robmarkcole** [comment]
Should this not be an issue on the custom updater repo instead? I am not a user of it FYI

**Comment by aptonline** [comment]
@robmarkcole not seen it in any other custom card/component I assumed it reads the version info from the component?

**Comment by Cyr-ius** [comment]
When looking at the source code of the pyupdate library, 
the recovery of the version is based on __version__

https://github.com/ludeeus/pyupdate/blob/master/pyupdate/ha_custom/custom_components.py
Line 142

**Comment by robmarkcole** [comment]
Should be resolved by https://github.com/robmarkcole/Hue-sensors-HASS/commit/c06791e0fa51a8ee9033f4c1fb73e3fde4ccfc86

**Comment by Ahmed-BRN** [comment]
thank you! works now

**Comment by aptonline** [comment]
Yep happy to report working for me too. Closing.
