### ISSUE TITLE
Freezing this repo - no new features accepted, please contribute to the official integration

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/Hue-sensors-HASS#142]
Now that there is an [official HA integration for Hue sensors](https://github.com/home-assistant/home-assistant/tree/dev/homeassistant/components/hue) I am freezing this repo - meaning I will **not be accepting any new features**. Instead I encourage contribution of features to the official HA codebase. I know many people rely on this repo e.g. for remotes, so will consider any PR which address breaking changes that affect this repo, but these are the only PR which will be considered.
Many thanks

**Comment by dm82m** [comment]
why are they adding support for motion sensor but skipping the support of remotes? why isnt your stuff directly merged into HA codebase?

**Comment by Mariusthvdb** [comment]
hi Rob, think I found a breaking change, please see https://github.com/robmarkcole/Hue-sensors-HASS/issues/146.

Not sure I can create a PR, my python skills are under par for that, but I do hope that the link and suggestion I provided could be a pointer for a solution? If not let me know what still lacks, so I can investigate further.

**Comment by robmarkcole** [comment]
Please create issues for breaking changes, no need to report them in this issue, so locking

**Comment by robmarkcole** [comment]
I changed my mind about this, as this CC really adds alot of functionality over the built in support. It remains an ambition to port this functionality over to the built in integration in time
