### ISSUE TITLE
HA 0.94.3: device_tracker.huesensor not found

### ISSUE THREAD

**Issue by Mariusthvdb** [robmarkcole/Hue-sensors-HASS#146]
Did post on the community, but for completeness also file an issue here about the device_tracker component not being found in HA 94.+ (94.3 in my case)

please see: https://community.home-assistant.io/t/hue-motion-sensors-remotes-custom-component/27176/1020?u=mariusthvdb for more details and discussion

config in package:

```
binary_sensor:
  - platform: huesensor
device_tracker:
  - platform: huesensor
sensor:
  - platform: huesensor
```

error:

![Schermafbeelding 2019-06-18 om 10 54 18](https://user-images.githubusercontent.com/33354141/59689838-a5b03080-91e0-11e9-867a-38241df4de99.jpg)

both sensor and binary_sensor work just fine and respond swiftly as before. Tried to move the device_tracker component out of the package (just in case) and into the device_tracker.yaml, but that yields the same error.

Only option for now is to disable the device_tracker, because with it HA won't restart, erroring out the config error

please have a look what could be done

maybe this contains some valid pointers to a solution, by @pnbruckner on his device_trackers code changes for HA 94: https://community.home-assistant.io/t/composite-device-tracker-platform/67345/215?u=mariusthvdb
thanks

**Comment by robmarkcole** [comment]
Yes looks like they split device tracker into several files https://github.com/home-assistant/home-assistant/tree/dev/homeassistant/components/device_tracker

**Comment by Mariusthvdb** [comment]
yes, the device_tracker logic has changed quite a bit, and, as shared in my first post above, some ideas of how to solve that exist.
Is this working for you, and will you be able to get it back 'online' ? Is there anything we can do to test this to assist doing so? pleas let us know, happy to do so.
