### ISSUE TITLE
Support for HACS

### ISSUE THREAD

**Issue by h4nc** [robmarkcole/Hue-sensors-HASS#147]
Hi,

as the title says custom_updater is depricated. The developer startet a new project called:
Home Assistant Community Store (HACS).

https://custom-components.github.io/hacs/#hacs-home-assistant-community-store

Could you please add this component to HACS?

thanks,
h4nc

**Comment by robmarkcole** [comment]
Please submit a PR if you want this feature, thanks

**Comment by h4nc** [comment]
I'm afraid I'm not able to do that.

**Comment by robmarkcole** [comment]
It really bugs me that people are so willing to open issues with feature requests but then unwilling to help out. Unless I receive a PR and that person is willing to provide ongoing support, this feature is not going to happen. Sorry

**Comment by robmarkcole** [comment]
OK turns out this is already supported
