### ISSUE TITLE
add this to HACS

### ISSUE THREAD

**Issue by ljmerza** [robmarkcole/Hue-sensors-HASS#156]
https://github.com/custom-components/hacs/blob/data/repositories/integration

**Comment by robmarkcole** [comment]
Please provide an explanation

**Comment by ljmerza** [comment]
You mention tracking updates with HACS but your custom component isnt added to HACS...

**Comment by robmarkcole** [comment]
OK created a PR

**Comment by inverse** [comment]
@robmarkcole this can be closed :+1:
