### ISSUE TITLE
HomeAssistance 0.98.2 wont see the sensor files in component folder

### ISSUE THREAD

**Issue by tipih** [robmarkcole/Hue-sensors-HASS#157]
Hi.

I get this error on HA 0.98.2
Platform error sensor.huesensor - Integration huesensor not found.
Platform error binary_sensor.huesensor - Integration huesensor not found.

I do have the following file structure
custom_components
   -------------------------->huesensor
                                     -------------> binary_sensor.py
                                                        device_tracker.py
                                                        sensor.py
                                                        __init__.py
                                                        manifest.json

What do I miss ? or have the file structure change ?
Im running HA on Docker under ubuntu
Filesystem is located at
/srv/homeautomation/hass-config

**Comment by raoulteeuwen** [comment]
I'm running HA 0.98.2 and don't see this on my Pi3b. What HA version did you come from? What version of the hue-sensor are you running (and have you changed that recently)? Your files are organised like https://github.com/robmarkcole/Hue-sensors-HASS/tree/master/custom_components/huesensor ?

**Comment by robmarkcole** [comment]
stale
