### ISSUE TITLE
Feature request: Add support for Hue Smart Button

### ISSUE THREAD

**Issue by Mincka** [robmarkcole/Hue-sensors-HASS#159]
Hello,

I bought a Philips Hue Smart Button and I would like to see it implemented in this component.
https://www2.meethue.com/en-us/p/hue-smart-button/046677553715

You will find hereunder the exposed device in the Hue hub:
```
"87": {
	"state": {
		"buttonevent": 1002,
		"lastupdated": "2019-11-16T11:48:24"
	},
	"swupdate": {
		"state": "noupdates",
		"lastinstall": "2019-11-16T10:54:58"
	},
	"config": {
		"on": true,
		"battery": 100,
		"reachable": true,
		"pending": []
	},
	"name": "Hue Smart button 2",
	"type": "ZLLSwitch",
	"modelid": "ROM001",
	"manufacturername": "Philips",
	"productname": "Hue Smart button",
	"diversityid": "8b18a40c-eb6a-40d7-a0af-eb0906613d41",
	"swversion": "2.21.0_r29784",
	"uniqueid": "00:17:88:01:06:06:81:5c-01-fc00",
	"capabilities": {
		"certified": true,
		"primary": true,
		"inputs": [
			{
				"repeatintervals": [
					800
				],
				"events": [
					{
						"buttonevent": 1000,
						"eventtype": "initial_press"
					},
					{
						"buttonevent": 1001,
						"eventtype": "repeat"
					},
					{
						"buttonevent": 1002,
						"eventtype": "short_release"
					},
					{
						"buttonevent": 1003,
						"eventtype": "long_release"
					}
				]
			}
		]
	}
}
```

We can see this is a new model ID, starting with "ROM" but it could be assimilated to the Dimmer remote ("RWL") and parsed as such.

I only changed four lines of code (cf. references to "ROM") in sensor.py and it works flawlessly! 😄 

```
ICONS = {
    "SML": "mdi:run",
    "RWL": "mdi:remote",
    "ROM": "mdi:remote",
    "ZGP": "mdi:remote",
    "FOH": "mdi:light-switch",
}
DEVICE_CLASSES = {"SML": "motion"}
ATTRS = {
    "SML": [
        "light_level",
        "battery",
        "last_updated",
        "lx",
        "dark",
        "daylight",
        "temperature",
        "on",
        "reachable",
        "sensitivity",
        "threshold",
    ],
    "RWL": ["last_updated", "battery", "on", "reachable"],
    "ROM": ["last_updated", "battery", "on", "reachable"],
    "ZGP": ["last_updated"],
    "FOH": ["last_updated"],
}


def parse_hue_api_response(sensors):
    """Take in the Hue API json response."""
    data_dict = {}  # The list of sensors, referenced by their hue_id.

    # Loop over all keys (1,2 etc) to identify sensors and get data.
    for sensor in sensors:
        modelid = sensor["modelid"][0:3]
        if modelid in ["RWL", "ROM", "SML", "ZGP"]:
            _key = modelid + "_" + sensor["uniqueid"][:-5]
            if modelid == "RWL" or modelid == "ROM":
                data_dict[_key] = parse_rwl(sensor)
            elif modelid == "ZGP":
                data_dict[_key] = parse_zgp(sensor)

        elif modelid == "FOH":  ############# New Model ID
            _key = modelid + "_" + sensor["uniqueid"][-5:]  ###needed for uniqueness
            data_dict[_key] = parse_foh(sensor)

    return data_dict
```

![image](https://user-images.githubusercontent.com/6184289/68996086-9e777680-0895-11ea-97a9-29f990aec2c8.png)

![image](https://user-images.githubusercontent.com/6184289/68996101-d8e11380-0895-11ea-8fda-01251a88b6ec.png)

Events: 1_click;1_click_up; 1_hold; 1_hold_up

The only thing not working is the battery level reporting, I don't know why since it is present at the same location than the property of the dimmer.

After pairing the button with the Hue hub, you must start the setup and leave it empty. If you do not start the setup, the button will not work (no LED feedback).

**Comment by KimRechnagel** [comment]
@Mincka the code you list above is the same as in the latest sensor.py file, but I do not see the smart button in the states list. What were the four changes you made to the sensor.py file?

**Comment by KimRechnagel** [comment]
Did you make changes to the binary_sensor.py file as well?

**Comment by KimRechnagel** [comment]
I had to remove redundant hue configuration. I was using both the discovery and the hue: bridge configuration in configuration.yaml. I commented out the hue: part, then the sensor showed up under states. Thanks Mincka.

**Comment by beatschubser** [comment]
Are multiple clicks possible yet? I can only seem to get 1_click and 1_hold as events.

**Comment by Mincka** [comment]
@beatschubser : As you can see in the `capabilities`, there is no multiple clicks events.

**Comment by robmarkcole** [comment]
Supported on remotes repo
