### ISSUE TITLE
Issues adding repository

### ISSUE THREAD

**Issue by jakebeans** [robmarkcole/Hue-sensors-HASS#163]
Not sure if I'm doing it wrong, but I copy the URL to the add repository page and it doesn't seem to add it.  I get this error in my system log:

19-11-23 04:11:01 INFO (MainThread) [hassio.store.git] Clone add-on https://github.com/robmarkcole/Hue-sensors-HASS repository
19-11-23 04:11:02 ERROR (MainThread) [hassio.utils.json] Can't read json from /data/addons/git/7c7e82cf/repository.json: [Errno 2] No such file or directory: '/data/addons/git/7c7e82cf/repository.json'
19-11-23 04:11:02 WARNING (MainThread) [hassio.store.data] Can't read repository information from /data/addons/git/7c7e82cf/repository.json

I'll keep looking at it, but I didn't have any issues adding the repository for ESPHome.

**Comment by robmarkcole** [comment]
Please use HACS
