### ISSUE TITLE
sensors stop showing light level/temp/lx when switched Off

### ISSUE THREAD

**Issue by Mariusthvdb** [robmarkcole/Hue-sensors-HASS#168]
Hi,

all of a sudden my motions sensors no longer show light level  or lx when switched off, either via the Hue app, or via the HA interface. Temp stays in the HA card, though the more-info on the entity shows it has gone too:

off:
<img width="357" alt="Schermafbeelding 2020-01-07 om 12 45 58" src="https://user-images.githubusercontent.com/33354141/71893414-e6a36e80-314b-11ea-9499-6b8fb9592cae.png">

on:
<img width="356" alt="Schermafbeelding 2020-01-07 om 12 47 04" src="https://user-images.githubusercontent.com/33354141/71893424-f0c56d00-314b-11ea-993e-157c3de53acb.png">

Before, all sensors showed all attributes, no matter their state. Only thing that was switched in/off was the motion sensing

Oddly enough, I have 2 sensors that are off (we're off already) and they do still show the attributes:

<img width="362" alt="Schermafbeelding 2020-01-07 om 12 49 00" src="https://user-images.githubusercontent.com/33354141/71893488-1d798480-314c-11ea-96e0-14d71e39a588.png">

any thoughts on what this might be?
I did experience severe issues adding a few extra accessories lately to the hub. As it turns out the Hub would only be[ able to hold 12 accessories](https://www2.meethue.com/en-us/p/hue-bridge/046677458478?fbclid=IwAR2PxNkdlvEs5oSg-J7Yp43l9cpqTl80cymcOIOn4W55jDJDr2Lt5yebcdw).... I have more than that.

Please have a look what might be causing this trouble. 

Could it be because of the late update to 103.5 Hassio? Did anything change in that department?
Thanks for your time.
Marius

**Comment by robmarkcole** [comment]
I dont keep on top on all the details in release notes, but I dont think this is anything on the HA side. Perhaps firmware update on the hub?

**Comment by Mariusthvdb** [comment]
oddly enough this seems to have resolved itself. Even before the latest App update.
noticed some inconsistent behavior (some motion sensor were on, and didn't show light details, others exactly the other way round) Everything now is back to normal.

thanks for chiming in!
