### ISSUE TITLE
New hue configuration 

### ISSUE THREAD

**Issue by mf-social** [robmarkcole/Hue-sensors-HASS#17]
https://home-assistant.io/components/hue/

I take it we need to rename the custom component?

**Comment by robmarkcole** [comment]
I need to look into it but assume yes. Next step is to rewrite this component to use the new hue library, then rewrite to use phue

**Comment by mf-social** [comment]
OK, I'll hang fire on upgrading until you come back to me, cheers 👍

**Comment by robmarkcole** [comment]
Appears the new lights components [access the bridge object ](https://github.com/home-assistant/home-assistant/blob/8742ce035a36b3a4a176123b620fe82e55d5a4e2/homeassistant/components/light/hue.py#L109) and this object has a method [get_ip_address()](https://github.com/studioimaginaire/phue/blob/00c85d8ce9790d7cc794d277af2d153c92c6009c/phue.py#L672) which can be [used in the setup](https://github.com/robmarkcole/Hue-sensors-HASS/blob/fb2fdcb866e13186d67cbb53602b06ac0b1733b5/custom_components/sensor/hue.py#L25) of hue sensors.

**Comment by mf-social** [comment]
So basically just change the name of the files to avoid a name conflict for the components and all should be ticketyboo? Like hue_sensor?

**Comment by robmarkcole** [comment]
That is the workaround for the time being

**Comment by mf-social** [comment]
Awesome, I'll give it a go in the morning 👍

Thanks for looking at it so quickly 😎

**Comment by mf-social** [comment]
Works fine - PR submitted for you.

**Comment by robmarkcole** [comment]
Thanks @mf-social this issue is resolved by https://github.com/robmarkcole/Hue-sensors-HASS/commit/85f01191cacebf3efee2575a4bf27fee0a80bd25
Cheers
