### ISSUE TITLE
Remote events "disapearing" ?

### ISSUE THREAD

**Issue by koying** [robmarkcole/Hue-sensors-HASS#171]
Not sure if it's a huesensor bug, a HA bug or just me missing something, but remote events "disappear" from my logbook.

Some pictures:
![](https://linx.semperpax.com/selif/07prj44v.png)
![](https://linx.semperpax.com/selif/dm05tgk8.png)

First one shows me clicking "Living remote" off, at 19:18
Second one shows me clicking it back on at 19:19, but the "off" event from 19:18 is gone.

Any idea?

**Comment by robmarkcole** [comment]
I guess HA is filtering the most relevant info to show. This is HA behaviour, rather than a bug or issue on this repo. 
Thanks

**Comment by koying** [comment]
Yep. I confirm the events are in the database, but not returned by the logbook API.
Sorry for the noise.

**Comment by koying** [comment]
More info:
HA specifically merge logbook entries on a 15 minute window, specifically for the "sensors" and "proximity" domains.

Very selfish demand, but would you consider moving the remotes to the "remote" domain, similar to the Harmony ones?
Besides the fact that it would solve my issue, it seems to actually make sense to me ;-)

**Comment by robmarkcole** [comment]
Thanks for the info, useful to know.
Please create a feature request, it is low down my list of priorities but perhaps someone will pick it up, or you could have a go?
