### ISSUE TITLE
HUE Remotes unavailable after update to V2.3

### ISSUE THREAD

**Issue by gambith** [robmarkcole/Hue-sensors-HASS#173]
After updating the custom component for HUE Sensors from V2.2 to V2.3 the HUE remotes become unavailable in HA, after reverting back to V2.2 the HUE remotes are available again.

Running Home Assistant 0.104.3

**Comment by Kugelfang666** [comment]
sam problem with the, the release notes state that the switches have been moved from sensor to remote domain. however, I don't find them there. do I also have to adapt the configuration.yaml?

**Comment by Kugelfang666** [comment]
I added 
```
remote:
  - platform: huesensor
```

an all entries came back. as announced this time as remote.XXX instead of sensor.XXX

**Comment by robmarkcole** [comment]
Added to readme
