### ISSUE TITLE
4_click and 4_hold gone in V2.3

### ISSUE THREAD

**Issue by Kugelfang666** [robmarkcole/Hue-sensors-HASS#174]
I just gave 2.3 a shot. unfortunately the 4_click and 4_hold states are gone. Instead if I press the 4th button on the remote the status in lovelace changes to a switch in off position. Is this behavior intended? For me its a major inconvenience since I was using the 4_hold quite a lot in my setup

**Comment by Mariusthvdb** [comment]
correct, this should ideally be restored to this:

<img width="551" alt="Schermafbeelding 2020-01-26 om 22 22 24" src="https://user-images.githubusercontent.com/33354141/73142060-c3087f80-408a-11ea-9ee3-a49b80a64406.png">

The remote isn't 'off', and it isn't a switch. It is on, as in ready fr the next click. state should be last clicked button...

have both the sensor.py and the new remote.py installed for easy comparison

**Comment by nmichell** [comment]
There's a couple lines of code that look to be changing this behavior in remote.py:
            if modelid in ["RWL", "ROM"]:
                button = data["state"][0];
                if button == "4":
                    return STATE_OFF

I tried commenting out those last two lines and button 4 is back to the original behavior.  I can't say what the author was intending here.

**Comment by Mariusthvdb** [comment]
while the file is to be redacted with the above correction, one might also change all references to 'sensor' and change that to 'remote', at least in the comments. ;-)

great this now is a remote package. thanks for the effort!

**Comment by robmarkcole** [comment]
Ping @koying for comment.

**Comment by koying** [comment]
Sorry about that.
I was testing the on/off behaviour of remotes and that slipped through into the PR.
Must be removed indeed, if some are using the different states of the remote's "off" button.

**Comment by Mariusthvdb** [comment]
adding to the above, shouldn't RWL and ROM code be taken out to the sensor.py file now?

**Comment by robmarkcole** [comment]
Resolved in https://github.com/robmarkcole/Hue-sensors-HASS/releases/tag/v2.4
@koying could you make a PR to tidy up sensor.py?
Thanks!
