### ISSUE TITLE
huesensor.sensor on v2.4

### ISSUE THREAD

**Issue by PadaThomas** [robmarkcole/Hue-sensors-HASS#178]
Hi,
Since the update v2.4 the error appears during the verification of the configuration.

> Platform error sensor.huesensor - No module named 'custom_components.huesensor.sensor'" 

When the line in sensor in configuration.yaml :
```
   - platform: huesensor
```
is delete there is no more error and everything works correctly.
Is this line still useful?

Thanks

**Comment by jelmerkk** [comment]
Same error here, but it doesn't work anymore. Sensors are unavailable.

**Comment by PadaThomas** [comment]
I only have dimmer switches and smart buttons. Formerly a sensor, now remote.
This is surely why everything works for me.

**Comment by jelmerkk** [comment]
Check. Had to rename my template sensors...

**Comment by robmarkcole** [comment]
there is no sensor.py now.
Note to self: check PR also update docs..!

**Comment by robmarkcole** [comment]
Corrected by 0837e82e81e18aaeef2f0219fab895708d1b5b05
