### ISSUE TITLE
new remote doesn't show state on more-info

### ISSUE THREAD

**Issue by Mariusthvdb** [robmarkcole/Hue-sensors-HASS#180]
the new remotes show fine in the Lovelace cards:

<img width="489" alt="Schermafbeelding 2020-01-27 om 23 43 25" src="https://user-images.githubusercontent.com/33354141/73220535-f583ac80-415e-11ea-86e1-a95ff5d13d83.png">

but show a switch toggle instead of the state in the more-info view:

my test adapted remote.py
<img width="365" alt="Schermafbeelding 2020-01-27 om 23 43 12" src="https://user-images.githubusercontent.com/33354141/73220561-03393200-415f-11ea-9c28-d540bab9c549.png">

this is with the newly officially released remote.py file:

<img width="354" alt="Schermafbeelding 2020-01-27 om 23 57 15" src="https://user-images.githubusercontent.com/33354141/73221320-d6861a00-4160-11ea-8b9c-ad489cd447f3.png">

please check and correct, @koying would you know how to resolve this?

**Comment by koying** [comment]
No. That's the default view for remotes, for whatever reason.

**Comment by Mariusthvdb** [comment]
in which case we should return to sensor.....
the toggle is useless, and confusing, and, we don't have the state. If this is a HA architecture thing, we can drop hope to change the more-info defaults.

@robmarkcole , what do you think? Its easy enough to set default remote icons and other stuff in the original sensor.py to have best of both worlds?

**Comment by robmarkcole** [comment]
It has been on the roadmap for a long time to implement remotes as remotes, and this is what a one would expect, so there will not be a rollback. There are a couple of options:

1. Suggest improvements to the remote implementation in HA (preferred)
2. Maintain a fork with the desired sensor behaviour 
3. Use a previous release of this repo
4. Is there a way to customise the look and feel?

I will leave this issue open for a while so we can hear other opinions/options

**Comment by Mariusthvdb** [comment]
fwiw, imho the remote would only be acceptable if it were implemented to full functionality, and not show a false state or functionality, even if it is only in the more-info.

appreciative of the wish to create an official HA remote, I don't think it is wise to create entities that are known to be incorrect..

(we shouldn't forget they are not remotes, but sensors, talking HUE language.) As I have demonstrated above, it is rather easy to adapt the sensor.py to create sensors mimicking remotes.

only thing is the don't belong to the HA domain remote.

I'd be the first one to jump to the remote package if we could properly make them behave as remotes, and show all states correctly. Happy to help and test in any way.

Until then, I'd suggest we need to keep things tidy, and not confuse users with this yet to be further developed remote.py. There must be a way to have the more-info show the state... let's keep looking ?

my 2cts.

**Comment by koying** [comment]
As a reminder, I wanted them as remotes because sensors are "block filtered" in the logbook.
What I mean by that is that everybody has his own use cases ;)

IMHO, remote being children of "toggle switches" in HA is probably what needs to be fixed.
It makes little sense, even for "real" remotes.

**Comment by Mariusthvdb** [comment]
Sure, appreciated, and you’re right , the native remote is somewhat odd.

Still, couldn’t we have the Hue remote behave like a proper HA remote , and show the toggle in the frontend ?

I’ve added the last_action in the attributes and showing the toggle would finalize it to be fully compliant...

**Comment by koying** [comment]
> Still, couldn’t we have the Hue remote behave like a proper HA remote , and show the toggle in the frontend ?

Not sure what you mean here. AFAIK, we have no control on that (or maybe on/off state, but that's what you asked to remove ;) )

> I’ve added the last_action in the attributes and showing the toggle would finalize it to be fully compliant...

Good idea. The Harmony remote calls it "current_activity". Maybe keep the same name?

**Comment by Mariusthvdb** [comment]
> Not sure what you mean here. 

well, if we're bound to the HA remote constraints, I feel the HA remote should follow 100% if possible, by showing the toggle in the state field, and not the button_event (which can be added to the attributes list)

> The Harmony remote calls it "current_activity". Maybe keep the same name?

that wouldn't be my choice tbh, since the Hue remotes don't switch activities, but light states...or control their brightness/color settings. 

I'd stick to the Hue api naming as much as possible. Button, or button_event would be that. I used last_action, as a maybe poor effort to stick to the last_updated. last_button_event might be perfect....

(full realize people can use the events for other scripts that involve current_activities, but that would be up to them, no reason to divert from HUE language for the Hue Custom component if you ask me)

**Comment by robmarkcole** [comment]
PR welcome

**Comment by Mariusthvdb** [comment]
Hey Rob,

Am I wrong in thinking the last_button_event has already been added by @koying ? No more PR needed for that ;-)
thanks! (still one of the most needed and used CC's in the HA config!)

**Comment by robmarkcole** [comment]
Good to know, but I really want to get this functionaltiy merged into HA so its not necessary to maintain this CC. Who is up for the challenge??
