### ISSUE TITLE
Since update to v2.5 (via HACS) Home-Assistant shows error

### ISSUE THREAD

**Issue by Flight777** [robmarkcole/Hue-sensors-HASS#182]
Hi there,

First of all thanks for creating this nifty little plugin :)

Unfortunately, I updated to v2.5 via HACS and now HASS (latest version) is showing an error for the component:

![image](https://user-images.githubusercontent.com/5236143/73382272-7eb5f300-42c7-11ea-9c36-6173202899fb.png)

How can I further troubleshoot this best for you?

**Comment by robmarkcole** [comment]
I am not too familiar with HACS. But the sensor.py file is now remotes.py

**Comment by Flight777** [comment]
So how can I correct this?

**Comment by robmarkcole** [comment]
OK we need to update `hacs.json`

**Comment by Flight777** [comment]
Ok :)

Is there a workaround for now for me such I can get it going again? 👍

**Comment by dalwhin** [comment]
rename the remotes.py back to sensor.py and it's working again.

**Comment by robmarkcole** [comment]
resolved in https://github.com/robmarkcole/Hue-sensors-HASS/releases/tag/v2.6

**Comment by dalwhin** [comment]
updated and quick checked. thanks a lot :-)
