### ISSUE TITLE
A little question

### ISSUE THREAD

**Issue by Vartkat** [robmarkcole/Hue-sensors-HASS#184]
Hi, 

As I'm a Home Assistant newbie I was browsing the HACS integrations and as I'm having troubles reading the light level of a Hue motion sensor I was wondering if this integration could help me. 
He is my story so far : 
1-I tried the motion sensor paired with a Conbe II =>  no light level (1 lux)
2-paired via an old Hue V1 hub, thought it would update the motion sensor and as I was able to read light level => light level succesfull reading
3- I paired (my supposed updated motion sensor) again directly with the Conbee II but the problem was still there. => no light level
4- Back via the Hue hub and now I don't have light level. => no light level

I was wondering if this integration could help me solve this problem.

For real, I'm sorry, but reading your github page doesn't tell me what is the purpose of this ? 
Is it to get more detailed data from a working motion sensor ? Is is only to get a special card in the lovelace interface ? The aim is not clear enough for me, perhaps I'm a little dumb but I need clarification.

Thanks for your help

Regards
V.

**Comment by robmarkcole** [comment]
Hi
It will create a binary sensor that will have an attribute for light level. We should improve the documentation on this repo. The forums are a great place for discussing this integration.
Thanks
