### ISSUE TITLE
Platform error sensor.huesensor

### ISSUE THREAD

**Issue by jschweizer78** [robmarkcole/Hue-sensors-HASS#185]
I get the following error with all version after 2.3 (2.4-2.6) when restarting Hass. 

Thu Jan 30 2020 21:01:08 GMT-0800 (Pacific Standard Time)
Platform error sensor.huesensor - No module named 'custom_components.huesensor.sensor'

**Comment by robmarkcole** [comment]
You must have some old code cached, probably in the integration folder, clear it out and restart HA

**Comment by jschweizer78** [comment]
Where is the integration folder???
