### ISSUE TITLE
ModuleNotFoundError: No module named 'hue_sensors'

### ISSUE THREAD

**Issue by Ashald** [robmarkcole/Hue-sensors-HASS#19]
Just installed Home Assistant `0.60.0` as a Docker container and that's what I see in log when I activate the plugin
```
Log Details (ERROR)
Sun Dec 17 2017 21:12:05 GMT-0500 (EST)

Error while setting up platform hue
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_component.py", line 171, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=self.hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sensor/hue.py", line 24, in setup_platform
    import hue_sensors as hs
ModuleNotFoundError: No module named 'hue_sensors'
```

**Comment by robmarkcole** [comment]
Thanks, tracking this issue here: https://github.com/robmarkcole/Hue-sensors-HASS/issues/19
Since this is an issue not with this repo but with the HASS component, I will close the issue here.
cheers

**Comment by robmarkcole** [comment]
OK I'm running 85f01191cacebf3efee2575a4bf27fee0a80bd25 on Docker (synology) and no errors. Let me know and please close this issue if the release resolves. Btw be sure to remove `hue` from your config.
Cheers

**Comment by michaelmaat** [comment]
After updating hass.io and hue-sensors-hass to 0.60 I ran into the same problem as Ashald.

Here is my config:
``` yaml
sensor:
  - platform: hue_sensor

hue:
  bridges:
    - host: 192.168.178.44
```

Removing the hue/bridges/host did fix the hue sensors, but my lights didn't show up anymore. So I put back the config and did a full reboot (``` hassio host reboot ```  instead of ``` hassio homeassistant restart ```) of my Pi. Now everything works again :)

**Comment by Ashald** [comment]
I'm running under Docker on Synology as well. I pulled the latest code from the repo and removed `hue` from the config but now I see:

```
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_component.py", line 171, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=self.hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sensor/hue_sensor.py", line 40, in setup_platform
    url = load_conf(filepath) + '/sensors'
  File "/config/custom_components/sensor/hue_sensor.py", line 26, in load_conf
    with open(filepath, 'r') as file_path:
FileNotFoundError: [Errno 2] No such file or directory: '/config/phue.conf'
```

There is indeed no `/config/phue.conf` in my `/config` but there is `phue-0017886c3a18.conf`. o_O Did I miss anything else?..

**Comment by Ashald** [comment]
P.S.: After I copied `phue-0017886c3a18.conf` to `phue.conf` it worked. But I'm not sure that was the right thing to do...

**Comment by Ashald** [comment]
P.P.S.: Also, if I remove
```yaml
hue:
```
from my config then I don't see my lights in HA... is that intentional? I'd rather see them there. Just wonder if it's incompatible with this package in any way.

**Comment by hanssep** [comment]
Confirming @michaelmaat "solution" works. This is an awesome addon but it should work with hue: component. Looking forward seeing this as an official component in next HASS release.

**Comment by robmarkcole** [comment]
Interesting, so reboot of Hassio is required. Cheers
