### ISSUE TITLE
Split out the hue hub from hub.py

### ISSUE THREAD

**Issue by rossdargan** [robmarkcole/Hue-sensors-HASS#2]
I really think for "correctness" we should look at splitting out the hue configuration code a bit like how (nest)[https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/nest.py] does it.

**Comment by robmarkcole** [comment]
@rossdargan I agree, however will also want to ensure compatability with the hue light components so may end up forking that too. Was going to wait and see what further feedback I get on https://github.com/home-assistant/home-assistant/pull/9449

**Comment by robmarkcole** [comment]
Verisure appears to be a good hub model model https://github.com/home-assistant/home-assistant/blob/31f17a91e655967067e3bf531bb240d84d74b148/homeassistant/components/binary_sensor/verisure.py
