### ISSUE TITLE
Migrate to Hue-sensors-phue

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/Hue-sensors-HASS#20]
To do: migrate Hue-sensors-HASS to use https://github.com/robmarkcole/Hue-sensors-phue in preparation for submission as a full component in HA.

**Comment by robmarkcole** [comment]
Created branch [dev-phue](https://github.com/robmarkcole/Hue-sensors-HASS/tree/dev-phue).

Currently I have copied `setup_platform() `from [hue.lights](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/light/hue.py) but I don't understand how the `bridge_id` is being returned by `discovery_info` since it appears `discovery_info` is empty. @andreacampi could you offer advice?
Cheers

**Comment by andreacampi** [comment]
Sure: in 0.60 the hue component handles both discovery and configuration; then it calls [`discovery.load_platform`](https://github.com/home-assistant/home-assistant/blob/1d579587c1d6605f144fb98f23935d7a40993660/homeassistant/components/hue.py#L196) that invokes hue.lights `setup_platform` passing the `bridge_id`.

Now that I look at this again, I suspect [this block](https://github.com/home-assistant/home-assistant/blob/1d579587c1d6605f144fb98f23935d7a40993660/homeassistant/components/light/hue.py#L98) is not called any more after that `bridge_id` change. Oops. That means that is auto discovery fails we never tell the user that they need to change their config. I should fix that.

**Comment by andreacampi** [comment]
In other words, you have to change [this](https://github.com/home-assistant/home-assistant/blob/1d579587c1d6605f144fb98f23935d7a40993660/homeassistant/components/hue.py#L196):

```
   discovery.load_platform(
            self.hass, 'light', DOMAIN,
            {'bridge_id': socket.gethostbyname(self.host)})
```

should become something like:

```
    PLATFORMS = ['light', 'sensor']

    for platform in PLATFORMS:
         discovery.load_platform(
            self.hass, platform, DOMAIN,
            {'bridge_id': socket.gethostbyname(self.host)})
```

**Comment by robmarkcole** [comment]
@andreacampi thanks for your suggestion, I've made the changes and the component is now functional. 

I understand now that your HueBridge object is a wrapper to the phue bridge, so I end up with some awkward syntax of `response = self.bridge.bridge.get_sensor_objects('name')` since there is no method on HueBridge for `get_sensor_objects()`. I am also seeing slow response to update the sensor state in HA, and in my logs:

`2017-12-21 06:58:34 WARNING (MainThread) [homeassistant.components.sensor] Updating hue sensor took longer than the scheduled update interval 0:00:01`

My question is, what changes do you recommend to improve performance? Cheers!

**Comment by technicalpickles** [comment]
Awesome! I took a quick look but didn’t see anything obviously slow. I’d take a look at the API call’s timing, but you might not be able to do much to speed that up much. You can at least log the time it takes to get a sense of it.

I was wondering if the hue component does any of the API calls, but it doesn't look like it. At most, it has instance of the phue `bridge` object that gets passed to the light platform.

**Comment by andreacampi** [comment]
Yeah I don't think you can do much about performance, other than reducing the polling interval (can't remember how from the top of my head).

**Comment by andreacampi** [comment]
BTW I agree with you `self.bridge.bridge.get_sensor_objects` is a bit ugly. I would do the same I did for the light platform, i.e. set up a proxy method in the main component. See the `set_light` method as an example.

So for example

    def get_sensor_objects(self, key):
      return self.bridge. get_sensor_objects(key)

It's not a big deal but it encapsulated `HueBridge` better and it gives us a central place to e.g. log etc. if we ever wanted to.

**Comment by robmarkcole** [comment]
@technicalpickles & @andreacampi I believe the slow performance may be an issue with the way Hue queries the API. There are [rate limits](http://rsmck.co.uk/hue) and [this issue ](https://github.com/studioimaginaire/phue/issues/109)suggests the polling by phue is inefficient. Could you guys [take a look](https://github.com/fingon/kodin-henki/commit/d30a518f191b1839af516ce462408958687025dd) and let me know what you think? 

If this is the case then I see no good reason to use phue as directly calling the API as I implemented previously performs well. Currently I am parsing the phue object rather than the json from the API so phue isn't adding any useful functionality in my opinion, but maybe I'm missing something? 
Cheers

**Comment by robmarkcole** [comment]
Complete in https://github.com/robmarkcole/Hue-sensors-HASS/commit/c01de37d36f0aa0ed9f49d307b5030b0cd76bbc5
