### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/Hue-sensors-HASS#204]
Highest priority is to add tests of all the parsing functions. Use pytest and integrate with CI following example of https://github.com/robmarkcole/HASS-data-detective

**Comment by robmarkcole** [comment]
Still require tests in `remote.py` for `parse_foh`, `parse_z3_rotary` and `parse_z3_switch` (both Lutron Aurora). Request these from @TPX01 and @barisahmet or if they can provide the data returned by the API for these devices

**Comment by barisahmet** [comment]
I will post data when I get home. Actually I have posted response before, in another issue.

https://github.com/robmarkcole/Hue-sensors-HASS/issues/188#issuecomment-580800865

Maybe it helps.
