### ISSUE TITLE
KeyError: 'hue' in remote.py

### ISSUE THREAD

**Issue by Mariusthvdb** [robmarkcole/Hue-sensors-HASS#218]
Never seen this before in my logs, and no reason to either..... didn't change anything in the setup

do have timing issues, after updating to 105.5, tough I do believe my remote sensors were created after that.

Any thoughts on how to mitigate this?
thanks for having a look.
```
2020-02-23 13:24:25 ERROR (MainThread) [homeassistant.components.remote] Error while setting up hue_custom platform for remote
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 159, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/hue_custom/remote.py", line 238, in async_setup_platform
    await data.async_update_info()
  File "/config/custom_components/hue_custom/remote.py", line 293, in async_update_info
    bridges = get_bridges(self.hass)
  File "/config/custom_components/hue_custom/__init__.py", line 15, in get_bridges
    for entry in hass.data[hue.DOMAIN].values()
KeyError: 'hue'
```

**Comment by Mariusthvdb** [comment]
ok, so I rebooted, and the issue didn't re-appear. Seems to be an issue of timing during startup.

Maybe this could be handled better in the CC? Maybe have a longer grace period, or a retry of sorts?

**Comment by azogue** [comment]
Hi @Mariusthvdb, 

Could you check if this is happening with the new version? (so it can be closed if it's fixed)

> Unless this is caused by the recently removed depency: HUE.

Sorry, that I don't understand. You have the `hue` integration configured in HA, right? (if not, this won't work)

**Comment by Mariusthvdb** [comment]
don't think I see it anymore, even before the latest update.

> You have the hue integration configured in HA, right? (if not, this won't work)
shouldn't this be safe-guarded? 
Especially since we can use the yaml configuration again for allowing groups and unavailable. People might have only configure Hue integration in the Yaml, and not configuration/integration ia the UI.

**Comment by azogue** [comment]
>Especially since we can use the yaml configuration again for allowing groups and unavailable. People might have only configure Hue integration in the Yaml, and not configuration/integration ia the UI.

It doesn't matter how do you configure the `hue` integration, manually or via UI. In fact, you should view the hue integration config in the UI menu, even when configured manually. Check that.

> shouldn't this be safe-guarded?

It is, in the `manifest.json`, it depends on hue. That ensures the setup is called after hue.

> don't think I see it anymore, even before the latest update.

@robmarkcole, this issue should be closed too.

Sure @Mariusthvdb agrees on that, right?

**Comment by azogue** [comment]
> In fact, you should view the hue integration config in the UI menu, even when configured manually. Check that.

**Note: you should use the official hue integration, not a customized one**
