### ISSUE TITLE
add multiple hue gateways

### ISSUE THREAD

**Issue by thundergreen** [robmarkcole/Hue-sensors-HASS#22]
unfortunately it does not work. I see 4_click in dev-states but it wont change when i push a button. And i have second hue platforn (deconz) with two remotes. would like to use both. Is that possible?

**Comment by robmarkcole** [comment]
I'm working on upgrading this component to use the new Hue hub component. Once finished that should handle multiple hubs I believe.

**Comment by thundergreen** [comment]
Means ATM it won't work with new hue component? There's already a fix for multiple hue but not pushed yet

**Comment by robmarkcole** [comment]
Working with 0.62 dev and should be backwards compatible, but no guarantees
