### ISSUE TITLE
moved sensor: no automatic renaming in hue_sensor-hassio frontend?

### ISSUE THREAD

**Issue by hvbhome** [robmarkcole/Hue-sensors-HASS#23]
please have a look,https://community.home-assistant.io/t/hue-motion-sensors-remotes-custom-component/27176/162?u=mariusthvdb

it seems the hue_sensor isnt automatically updating after all ?
Ive changed a sensor and moved it, my manually created rest_sensors 

--edit--
stop this here, moved over to above link

**Comment by robmarkcole** [comment]
I recall this was resolved
