### ISSUE TITLE
Extraneous Warning in Z3 Switch Parsing

### ISSUE THREAD

**Issue by cmptrgeekken** [robmarkcole/Hue-sensors-HASS#230]
I recently noticed that I had a ton of warnings getting logged from the Hue application, with the same message:
```
Log Details (WARNING)
Logger: root
First occured: March 11, 2020, 3:15:06 PM (61840 occurences)
Last logged: 8:34:26 AM

1002
```

Digging through the code, it looks like a `logging.warn()` got put in for debugging and wasn't removed. I've linked the line number below:

https://github.com/robmarkcole/Hue-sensors-HASS/blob/e4ca16dec37602333597cb8693007f68f2546cd6/custom_components/huesensor/hue_api_response.py#L210

**Comment by azogue** [comment]
> Digging through the code, it looks like a logging.warn() got put in for debugging and wasn't removed

It was exactly that, sorry for the inconvenience. 2.15 should remove that
