### ISSUE TITLE
Drop support for motion sensors?

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/Hue-sensors-HASS#234]
We are duplicating support for motion sensors, as these are supported by HA officially. Propose dropping support for them and focussing soley on remotes (not currently supported by HA). This would simplify troubleshooting, streamline the codebase, and clarify the purpose of this CC. Are there any **strong arguments for continued support of the motion sensors?**
Thanks for your comments

**Comment by Mariusthvdb** [comment]
Yes, very strong arguments:

The core sensors suffer enormously from the constant 'unavailable' issue the full core Hue integration suffers. While the Custom integration sensors are rock solid, as they have always been.


Please, please dont drop support for the sensors. Way to go at the moment is installing the Custom integration and disable core sensors.

I know it is supposed to be the other way round, have even called it heresy..., but as it stand, this is what it is. 

Let me stress again: please dont drop support.

(just search the community for Hue + unavailable and let is speak for it self)
Also, the custom sensors hold much more info, so before that would be absorbed in the core sensors, no dropping please...

**Comment by robmarkcole** [comment]
There are technical reasons why the official integration is not satisfactory, but then again the approach in thie CC is also causing different issues. 

Another option is to split out the remote functionality into a seperate integration, with a goal if integrating that into HA. The sensors support can then be continued in this repo. This would make it easier for people who just want remotes, and hopefully reduce the number of issues raised

**Comment by Mariusthvdb** [comment]
HI Rob,

Not really sure what issues this CC is causing, but may people have tested with and without the CC, and this didn't make a significant difference for the logged errors.

It didn't in the former architecture, and it doesn't now. All rather extensively documented in the various issues raised and on the community.

If you'd split, I would certainly welcome the opportunity that brings, to keep the sensors, and yes, integrate the remotes. Then again, Balloob has stated on mor than 1 occasion he feels the remotes are not going to be updated more than each 5 seconds, which would render them useless as triggers for core logic. So, there also reason to keep the remotes in the CC for that alone (I don't use that so am not bothered by it, by many other users do)

**Comment by azogue** [comment]
> Another option is to split out the remote functionality into a seperate integration, with a goal of integrating that into HA. The sensors support can then be continued in this repo. This would make it easier for people who just want remotes, and hopefully reduce the number of issues raised

I think that could be a very good idea, so this CC in its current form could be available for anyone not using the sensors in HA Core, and a more simpler one with just the remotes could live for the time until gets integrated in HA (which could be forever btw)

**Comment by Mariusthvdb** [comment]
Am I wrong in thinking we can already do that, but not setting the binary_sensor in the config?
