### ISSUE TITLE
Split out remotes

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/Hue-sensors-HASS#237]
As discussion in https://github.com/robmarkcole/Hue-sensors-HASS/issues/234 split out remotes into standalone repo `Hue-remotes-HASS`

**Comment by robmarkcole** [comment]
Created https://github.com/robmarkcole/Hue-remotes-HASS

**Comment by netrene** [comment]
I´m not happy about this change. I use only remotes which applies probably to the majority of the users of this component as the sensors are natively supported by HA.

All users that want to keep remotes running now need now to manually install hue remotes (no HACS Support) and to reconfigure.

Wouldn´t it have been more logic to split out the sensors that most likely not so many people use?

Cheers René

**Comment by robmarkcole** [comment]
I welcome a PR to add HACS support. I have (literally) my hands full with a new born baby, otherwise it wouldn’t take long

**Comment by robmarkcole** [comment]
Done
