### ISSUE TITLE
Cannot find Hue remotes

### ISSUE THREAD

**Issue by rogersmj** [robmarkcole/Hue-sensors-HASS#242]
I'm struggling to get my two Hue remotes to show up in Home Assistant. I used a very old version of this component years ago, and they worked back then, but at some point it stopped working so recently I deleted that and installed the current version from HACS. However, I can't find the remotes.

I'm on the latest of everything as of this writing (HA 0.107.1, Hue Sensor Advanced v3.0 (HACS)).

I installed via HACS and then added the following:

```
binary_sensor:
  - platform: huesensor
sensor:
  - platform: huesensor
```

"Sensor" isn't in the docs but in reading through some other issues trying to figure out what was going on, I saw someone mention that so I tried adding it.

But when looking in devices, I don't see my remotes. In the HA log, I see this:

```
  File "/usr/src/homeassistant/homeassistant/config.py", line 752, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 277, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.huesensor.sensor'
```

Other than the above, I don't see anything else in the log related to Hue/HueSensor aside from the typical warning about using a third-party custom component, which implies that the custom component is indeed loading.

I am using the official Hue integration in HA, so I'm wondering if there's some sort of conflict there. I haven't deleted it/unlinked it or whatever. Do I need to do that? I see two Phillips Hue integrations:

![image](https://user-images.githubusercontent.com/20134/77128962-8de43200-6a28-11ea-9b52-e2098f50ac97.png)

Unsure where to go from here and would appreciate some guidance.

**Comment by robmarkcole** [comment]
Remotes available via HACS

**Comment by rogersmj** [comment]
@robmarkcole I'm sorry what does that mean? "Remotes available via HACS"? Yes, I installed this from HACS and I can't get the remotes working.

**Comment by Kugelfang666** [comment]
There are now two custom components,
Effectively the remotes function has been stripped from this CC and put into a new Custom component
