### ISSUE TITLE
Homeassistant 0.60.1 has an updated hue.py which breaks the dev-phue version

### ISSUE THREAD

**Issue by jimbob1001** [robmarkcole/Hue-sensors-HASS#25]
Homeassistant 0.60.1 has an updated hue.py which breaks the dev-phue version of sensors. I tried to edit the new hue.py as per the changes in your readme instructions but it didn't work, throwing up an error about platforms

**Comment by jimbob1001** [comment]
Actually, it does work (missed a line when I did the copy/paste!). However, the version of hue.py in the custom_component folder in this repo is now out of date

**Comment by robmarkcole** [comment]
Brilliant thanks for the heads up. Could you submit a PR with your working version? 

I had a feeling there would be more changes to hue so waiting until its settled before submitting hue sensors to HA.
Cheers

**Comment by jimbob1001** [comment]
I can't today as I only have access to my phone (hence the bad copy/paste before) but will endeavour to at some point.
Do you think this is ready to be merged into homeassistant - seems to work great for me
Cheers,
James

**Comment by robmarkcole** [comment]
Based on past experience I'm certain there is more work to do before merging, but making the PR is the start of getting real feedback on the code 👍

**Comment by MartinBpunkt** [comment]
Same here. When a new version is online I will test too. Thank you so much for the fast reactions.

**Comment by jimbob1001** [comment]
have tried submitting a PR [here](https://github.com/robmarkcole/Hue-sensors-HASS/pull/26) to update the version of hue.py so it works again in home assistant 0.60.1

**Comment by robmarkcole** [comment]
Should be fixed by https://github.com/robmarkcole/Hue-sensors-HASS/commit/1792ad0d1c213a4102dddb784d239485d69812e8
