### ISSUE TITLE
No 'version' key in the manifest file

### ISSUE THREAD

**Issue by schol478** [robmarkcole/Hue-sensors-HASS#251]
Hi,

Is it possible to solve this issue before the new version of HA

No 'version' key in the manifest file for custom integration 'huesensor'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'huesensor'

Kind Regards

**Comment by robmarkcole** [comment]
It is there, you have an old version unless I am mistaken 

https://github.com/robmarkcole/Hue-sensors-HASS/blob/88cae74cf42c25a8490bba4eb8d4e82930381370/custom_components/huesensor/manifest.json#L6

**Comment by schol478** [comment]
In HACS only the version 3.0 is available. Manual installation will solve it.
