### ISSUE TITLE
Cant get the plugin working HASSIO 0.60.1

### ISSUE THREAD

**Issue by Kugelfang666** [robmarkcole/Hue-sensors-HASS#29]
Dear all, 

I currently have HASSIO v 0.60.1 running on a Raspberry pi3. Hassio is already connected to my hue bridge and I can operate all lights. In fact I already set up the motion sensors via templating. However, it would be great to also have the dimmer-switches avaliabe in HASSIO. 

Unfortunately, I can’t get this plugin to work. I did place both the hue_sensors and the hue_sensor.py in the custom_components/sensors. However, if I add 

sensor:
  - platform: hue_sensor

To my config hassio does not reboot anymore. It would be great if someone could help me out to get this working.

**Comment by robmarkcole** [comment]
Please can we use the HA forums for config issues, and keep Github issues for code issues. Cheers
