### ISSUE TITLE
Split out protocol specific functionality

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/Hue-sensors-HASS#3]
As in https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/sensor/dht.py (pulling in a Github release) I need to split out the protocol specific functionality as per https://github.com/home-assistant/home-assistant/pull/9449

Split out parsing functions

**Comment by robmarkcole** [comment]
@rossdargan could you try out the [dev branch](https://github.com/robmarkcole/Hue-sensors-HASS/tree/dev) which addresses this issue? Cheers

**Comment by robmarkcole** [comment]
I broke out my hue_sensors functionality into a separate .py file, could be useful for debugging. 
Hopefully I get the component published soon.

**Comment by rossdargan** [comment]
Hi Rob... I might be imagining this but I'm sure you asked for the json from the tap sensor... here it is {
    "state": {
        "buttonevent": 34,
        "lastupdated": "2017-10-08T13:56:13"
    },
    "config": {
        "on": true
    },
    "name": "Lounge",
    "type": "ZGPSwitch",
    "modelid": "ZGPSWITCH",
    "manufacturername": "Philips",
    "uniqueid": "00:00:00:00:00:43:01:39-f2"
}

**Comment by robmarkcole** [comment]
Thanks Ross.
This component is finished now, just working on tests
