### ISSUE TITLE
Warning on update time

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/Hue-sensors-HASS#32]
Getting the following warning, to investigate.
```
2018-01-16 07:22:53 WARNING (MainThread) [homeassistant.components.sensor] Updating hue sensor took longer than the scheduled update interval 0:00:00.100000
```

**Comment by flecmart** [comment]
Can confirm that same behavior in my setup. Sensors seem to integrate well, though.

**Comment by zepixir** [comment]
Yes, get a ton of those messages myself.
Seems to also generate this:

`ERROR (MainThread) [homeassistant.core] Timer got out of sync. Resetting`

Are others also getting this?

But everything works perfectly, so seems like the only problem is spamming in log.

**Comment by mf-social** [comment]
I didn't get many of these, maybe 1 or 2 a day until the last week.

Can't say exactly when it happened but my log is literally flooded with them every minute now.

Also, whilst I'm here, have you seen the PR for a new version of the hue lights component in homeassistant?

**Comment by zepixir** [comment]
Timer got out of sync is not because of this component I think. Was just a coincidence. when having 2 sec update I just get errors at startup, not after.

**Comment by robmarkcole** [comment]
This is known behaviour, please change scan_inteval.
I’m aware of the PR.
Cheers

**Comment by hvbhome** [comment]
changing scan interval might alleviate somewhat, but still the amount of errors is horrific...
ive made 2 counters for error and warnings, and wish i hadn't ;-(0

a lead might be the custom_ui, i have been experimenting with the phone sensor made by the component (cant get it to show the mdi: icon) and asked @andrey-git how to take it out of the global custom_ui on my system. https://github.com/andrey-git/home-assistant-custom-ui/issues/109 
Can be done with the option `custom_ui_state_card: null` hence i did that.

From that moment on, logging stopped my system, and the little grey popup in Hassio mentioning a system event kept on popping up. AS a matter of fact, it wouldn't leave at all..

takin out the custom_ui : null option calmed it down immediately . It proved to be related, and so might also be in the case of the other log-flooding.
Worth trying, at least.
Thought id share, cheers,
Marius

**Comment by popsyann** [comment]
Found it. Sorry!

**Comment by raoulteeuwen** [comment]
(was looking for it as well ... found "scan_interval" on https://www.home-assistant.io/docs/configuration/platform_options/ )
