### ISSUE TITLE
KeyError:'lux'

### ISSUE THREAD

**Issue by TheCellMC** [robmarkcole/Hue-sensors-HASS#38]
I'm getting this error when HASS boots
```
2018-01-21 09:39:45 ERROR (MainThread) [homeassistant.components.sensor] Error on device update!
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 217, in async_add_entity
    yield from entity.async_device_update(warning=False)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 306, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.6/asyncio/futures.py", line 332, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sensor/hue.py", line 214, in update
    self._hue_id]['lux']
KeyError: 'lux'
```

And here is the response from Philips Hue:
`{"1":{"state":{"daylight":true,"lastupdated":"2018-01-21T08:05:00"},"config":{"on":true,"configured":true,"sunriseoffset":30,"sunsetoffset":-30},"name":"Daylight","type":"Daylight","modelid":"PHDL00","manufacturername":"Philips","swversion":"1.0"},"2":{"state":{"temperature":1725,"lastupdated":"2018-01-21T08:43:39"},"swupdate":{"state":"noupdates","lastinstall":null},"config":{"on":true,"battery":100,"reachable":true,"alert":"none","ledindication":false,"usertest":false,"pending":[]},"name":"Hue temperature sensor 1","type":"ZLLTemperature","modelid":"SML001","manufacturername":"Philips","swversion":"6.1.0.18912","uniqueid":"00:17:88:01:02:12:dc:d0-02-0402"},"3":{"state":{"presence":false,"lastupdated":"2018-01-21T08:44:02"},"swupdate":{"state":"noupdates","lastinstall":null},"config":{"on":true,"battery":100,"reachable":true,"alert":"none","ledindication":false,"usertest":false,"sensitivity":0,"sensitivitymax":2,"pending":[]},"name":"Kitchen Sensor","type":"ZLLPresence","modelid":"SML001","manufacturername":"Philips","swversion":"6.1.0.18912","uniqueid":"00:17:88:01:02:12:dc:d0-02-0406"},"4":{"state":{"lightlevel":16455,"dark":false,"daylight":false,"lastupdated":"2018-01-21T08:44:07"},"swupdate":{"state":"noupdates","lastinstall":null},"config":{"on":true,"battery":100,"reachable":true,"alert":"none","tholddark":13331,"tholdoffset":7000,"ledindication":false,"usertest":false,"pending":[]},"name":"Hue ambient light sensor 1","type":"ZLLLightLevel","modelid":"SML001","manufacturername":"Philips","swversion":"6.1.0.18912","uniqueid":"00:17:88:01:02:12:dc:d0-02-0400"},"9":{"state":{"buttonevent":1002,"lastupdated":"2018-01-21T07:52:07"},"swupdate":{"state":"noupdates","lastinstall":null},"config":{"on":true,"battery":100,"reachable":true,"pending":[]},"name":"Kitchen switch","type":"ZLLSwitch","modelid":"RWL021","manufacturername":"Philips","swversion":"5.45.1.17846","uniqueid":"00:17:88:01:10:5e:e1:eb-02-fc00"},"14":{"state":{"buttonevent":1002,"lastupdated":"2018-01-21T08:10:23"},"swupdate":{"state":"noupdates","lastinstall":null},"config":{"on":true,"battery":100,"reachable":true,"pending":[]},"name":"Living room switch","type":"ZLLSwitch","modelid":"RWL021","manufacturername":"Philips","swversion":"5.45.1.17846","uniqueid":"00:17:88:01:10:6f:1b:10-02-fc00"},"15":{"state":{"status":0,"lastupdated":"2018-01-21T08:10:33"},"config":{"on":true,"reachable":true},"name":"Dimmer Switch 14 SceneCycle","type":"CLIPGenericStatus","modelid":"PHWA01","manufacturername":"Philips","swversion":"1.0","uniqueid":"WA0001","recycle":true},"16":{"state":{"temperature":1905,"lastupdated":"2018-01-21T08:44:21"},"swupdate":{"state":"noupdates","lastinstall":null},"config":{"on":true,"battery":100,"reachable":true,"alert":"none","ledindication":false,"usertest":false,"pending":[]},"name":"Hue temperature sensor 2","type":"ZLLTemperature","modelid":"SML001","manufacturername":"Philips","swversion":"6.1.0.18912","uniqueid":"00:17:88:01:02:12:f7:ad-02-0402"},"17":{"state":{"presence":false,"lastupdated":"2018-01-21T08:31:31"},"swupdate":{"state":"noupdates","lastinstall":null},"config":{"on":true,"battery":100,"reachable":true,"alert":"none","ledindication":false,"usertest":false,"sensitivity":1,"sensitivitymax":2,"pending":[]},"name":"Corridor","type":"ZLLPresence","modelid":"SML001","manufacturername":"Philips","swversion":"6.1.0.18912","uniqueid":"00:17:88:01:02:12:f7:ad-02-0406"},"18":{"state":{"lightlevel":8874,"dark":true,"daylight":false,"lastupdated":"2018-01-21T08:41:30"},"swupdate":{"state":"noupdates","lastinstall":null},"config":{"on":true,"battery":100,"reachable":true,"alert":"none","tholddark":11228,"tholdoffset":7000,"ledindication":false,"usertest":false,"pending":[]},"name":"Hue ambient light sensor 2","type":"ZLLLightLevel","modelid":"SML001","manufacturername":"Philips","swversion":"6.1.0.18912","uniqueid":"00:17:88:01:02:12:f7:ad-02-0400"},"19":{"state":{"status":0,"lastupdated":"2018-01-21T08:32:16"},"config":{"on":true,"reachable":true},"name":"MotionSensor 17.Companion","type":"CLIPGenericStatus","modelid":"PHA_STATE","manufacturername":"Philips","swversion":"1.0","uniqueid":"MotionSensor 17.Companion","recycle":true},"27":{"state":{"temperature":1927,"lastupdated":"2018-01-21T08:44:39"},"swupdate":{"state":"noupdates","lastinstall":null},"config":{"on":true,"battery":100,"reachable":true,"alert":"none","ledindication":false,"usertest":false,"pending":[]},"name":"Hue temperature sensor 3","type":"ZLLTemperature","modelid":"SML001","manufacturername":"Philips","swversion":"6.1.0.18912","uniqueid":"00:17:88:01:02:12:d9:97-02-0402"},"28":{"state":{"presence":false,"lastupdated":"2018-01-20T22:26:12"},"swupdate":{"state":"noupdates","lastinstall":null},"config":{"on":true,"battery":100,"reachable":true,"alert":"none","ledindication":false,"usertest":false,"sensitivity":2,"sensitivitymax":2,"pending":[]},"name":"Dining Room sensor","type":"ZLLPresence","modelid":"SML001","manufacturername":"Philips","swversion":"6.1.0.18912","uniqueid":"00:17:88:01:02:12:d9:97-02-0406"},"29":{"state":{"lightlevel":0,"dark":true,"daylight":false,"lastupdated":"2018-01-21T08:45:00"},"swupdate":{"state":"noupdates","lastinstall":null},"config":{"on":true,"battery":100,"reachable":true,"alert":"none","tholddark":13665,"tholdoffset":7000,"ledindication":false,"usertest":false,"pending":[]},"name":"Hue ambient light sensor 3","type":"ZLLLightLevel","modelid":"SML001","manufacturername":"Philips","swversion":"6.1.0.18912","uniqueid":"00:17:88:01:02:12:d9:97-02-0400"},"30":{"state":{"temperature":null,"lastupdated":"none"},"swupdate":{"state":"noupdates","lastinstall":null},"config":{"on":false,"battery":null,"reachable":false,"alert":"none","ledindication":false,"usertest":false,"pending":[]},"name":"Hue temperature sensor 4","type":"ZLLTemperature","modelid":"SML001","manufacturername":"Philips","swversion":"6.1.0.18912","uniqueid":"00:17:88:01:02:12:d6:74-02-0402"},"31":{"state":{"presence":null,"lastupdated":"none"},"swupdate":{"state":"noupdates","lastinstall":null},"config":{"on":false,"battery":null,"reachable":false,"alert":"none","ledindication":false,"usertest":false,"sensitivity":1,"sensitivitymax":2,"pending":[]},"name":"Hue motion sensor 1","type":"ZLLPresence","modelid":"SML001","manufacturername":"Philips","swversion":"6.1.0.18912","uniqueid":"00:17:88:01:02:12:d6:74-02-0406"},"32":{"state":{"lightlevel":null,"dark":null,"daylight":null,"lastupdated":"none"},"swupdate":{"state":"noupdates","lastinstall":null},"config":{"on":false,"battery":null,"reachable":false,"alert":"none","tholddark":16000,"tholdoffset":7000,"ledindication":false,"usertest":false,"pending":[]},"name":"Hue ambient light sensor 4","type":"ZLLLightLevel","modelid":"SML001","manufacturername":"Philips","swversion":"6.1.0.18912","uniqueid":"00:17:88:01:02:12:d6:74-02-0400"},"33":{"state":{"status":0,"lastupdated":"2018-01-21T07:52:17"},"config":{"on":true,"reachable":true},"name":"Dimmer Switch 9 SceneCycle","type":"CLIPGenericStatus","modelid":"PHWA01","manufacturername":"Philips","swversion":"1.0","uniqueid":"WA0001","recycle":true}}`

**Comment by robmarkcole** [comment]
I parsed your data with the hue-sensors library and got no errors. Is this an intermittent issue?



```python
import hue_sensors as hs
```


```python
hs.__version__
```




    1.2




```python
filename = "/Users/robincole/Desktop/hue_error_issue.json"
```


```python
response = hs.load_json_file(filename)
```


```python
data = hs.parse_hue_api_response(response)
```


```python
data
```




    {'RWL_10-02': {'battery': 100,
      'last_updated': ['2018-01-21', '08:10:23'],
      'model': 'RWL',
      'name': 'Living room switch',
      'state': '1_click'},
     'RWL_eb-02': {'battery': 100,
      'last_updated': ['2018-01-21', '07:52:07'],
      'model': 'RWL',
      'name': 'Kitchen switch',
      'state': '1_click'},
     'SML_74-02': {'battery': None,
      'last_updated': ['none'],
      'light_level': 'No light level data',
      'model': 'SML',
      'name': 'Hue motion sensor motion 1',
      'state': 'off',
      'temperature': 'No temperature data'},
     'SML_97-02': {'battery': 100,
      'dark': True,
      'daylight': False,
      'last_updated': ['2018-01-20', '22:26:12'],
      'light_level': 0,
      'lux': 1.0,
      'model': 'SML',
      'name': 'Dining Room motion sensor',
      'state': 'off',
      'temperature': 19.27},
     'SML_ad-02': {'battery': 100,
      'dark': True,
      'daylight': False,
      'last_updated': ['2018-01-21', '08:31:31'],
      'light_level': 8874,
      'lux': 7.71,
      'model': 'SML',
      'name': 'motion Corridor',
      'state': 'off',
      'temperature': 19.05},
     'SML_d0-02': {'battery': 100,
      'dark': False,
      'daylight': False,
      'last_updated': ['2018-01-21', '08:44:02'],
      'light_level': 16455,
      'lux': 44.2,
      'model': 'SML',
      'name': 'Kitchen motion Sensor',
      'state': 'off',
      'temperature': 17.25}}

**Comment by robmarkcole** [comment]
Please see [here](https://github.com/robmarkcole/Hue-sensors-HASS/tree/master/debugging_issues/Lux_issue). What is the device id causing your issue and does anything look strange about its data? Cheers

**Comment by robmarkcole** [comment]
From @mf-social 

Robin,

STOP!

(pauses for effect - love a bit of drama 😉  )

In the other issue I said I think the sensor is somehow now hardcoded in the python.  **It is** (even if you don't know it, or it shouldn't be) but **the important thing is it's not a problem**.

Here's what I have done to check everything out, but if you need any more info then let me know....

I have grep'd my entire install to ensure that there are no erroneous references to sensor platform hue.

I completely removed both hue.py and sensor/hue.py from my system, I deleted the database and rebooted the pi.

No sensors as expected and, crucially, no errors complaining that it cannot set up the sensor hue platform, so there are definitely no references to it in my system

Re-add only the hue.py, restart homeassistant, **persistent notification complains that it cannot find sensor.hue**.  I have **not** re-included that platform, so it MUST be hard-coded in to your hue.py somewhere.

Reintroduce sensor/hue.py and all errors disappear, and the hue sensors return.

The only ting you need to do to fix this issue is **remove** the instruction to include

```
sensor:
  - platform: hue
```

As that is what is causing the problem (maybe an endless loop or something)

Hope this helps.

**Comment by mf-social** [comment]
I'm confused, I posted that in the issue you generated (#40)  in relation to my previous issue (#37), I  think that the duplicate device id you're seeing in (#40) is because of some kind of endless loop but I don't understand python anywhere near enough to dive in and help.

If it fixes this issue too, happy days, but I did not get this error, and hadn't seen this issue so not sure why the comment was moved here.

**Comment by robmarkcole** [comment]
@mf-social yes I was confused, moved to your original issue and reopened. Cheers

**Comment by TheCellMC** [comment]
Okay, so it seems that my Philips Hue sensor was faulty, as it was not reporting it's temperature and luminosity to the hub. So I removed it from my Philips Hue Hub and I'm not getting this problem with my other Philips motion sensors.

**Comment by willfinnigan** [comment]
My sensors has randomly stopped working out of the blue..  its not reporting luminosity to the hub anymore :(  Anyway to get this working only for motion?   Or if anyone figures out a way to magically fix the sensor I'd love to know..  tried new batteries, renaming and restarting the hub to no avail.
