### ISSUE TITLE
Hassio error with HA 0.63.1

### ISSUE THREAD

**Issue by raoulteeuwen** [robmarkcole/Hue-sensors-HASS#46]
Hi.

I've updated to HA 0.63.1, am on hue.py d1d6081 (don't know where i can see what version apart from that GitHub-id) and get the following in my log:

"  File "/config/custom_components/sensor/hue.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax"

I've tried to create a JSON and parse it, but i'm not familiair with doing this. I found a setup.py and setup.cfg in the tar-file, as well as a hue_sensors.py. What command should i do on the prompt on my mac? "Python hue_sensors.py <file_name>"? When i do that, i get 

"Traceback (most recent call last):
  File "hue_sensors.py", line 6, in <module>
    import requests
ImportError: No module named requests"

Please find the JSON in txt format attached (GitHub doesn't allow uploading of JSON?).

[hue_raoul.txt](https://github.com/robmarkcole/Hue-sensors-HASS/files/1721579/hue_raoul.txt)

**Comment by robmarkcole** [comment]
Hi raul, you don't have requests installed, you need to` pip install requests`.
As for your issue, please delete your custom_components folder and re download this repo. 
Cheers

**Comment by raoulteeuwen** [comment]
Hi Rob. Thank you for the reply. I'm on hass.io. It worked for 2 weeks. I think the update of HASS might have wrecked it. How do i pip install request on hass.io on a Rpi3?

**Comment by robmarkcole** [comment]
Hi again, I’m not sure but expect you can SSH in to Hassio and perform the install. Il refer you to the docs or HA forum for more info on that.
Re Hassio I haven’t tested 0.63. There could be updates to the Hue hub component but I haven’t checked yet, will look tomorrow. Cheers

**Comment by raoulteeuwen** [comment]
Installed another SSH client to see whether i could get closer to OS level, but i think hassio prevents me from getting close. SSH-ing in, i get "Our Cli:
$ hassio help" and on executing that, i get a limited set of possible commands. Will wait a while to see whether more people run into problems upgrading, maybe reinstall completely :-|.

**Comment by robmarkcole** [comment]
OK I just updated my Hassio to HA 0.63.1 and my hue custom files had disappeared. I had to add them again, then `hassio host reboot` for changes to take effect. Please try the same. All working now for me

**Comment by hvbhome** [comment]
doesnt sound good....
any other files gone after updating..?

btw 0.63.2 is up ;-)

**Comment by raoulteeuwen** [comment]
Somehow i just could not get Hue back on my hass.io. Since i was already considering switching to hassbian, i thought i might as well, so currently trying to configure that. May i take the opportunity to thank you for your work @robmarkcole !
