### ISSUE TITLE
iPhone??

### ISSUE THREAD

**Issue by hvbhome** [robmarkcole/Hue-sensors-HASS#47]
Hi Rob,

Please don't laugh at me for this, but I never seem to understand what your iPhone is doing in the group....
Surely it doesn't get its place there from your sensor..? 

Sorry,
Marius

**Comment by robmarkcole** [comment]
Hi, the Hue iPhone app allows you to configure presence detection via geofencing. It’s actually how I’m doing presence detection.
Cheers

**Comment by hvbhome** [comment]
is that based on the 'home location' under Advanced?
I have that set, but don't see the iPhone as a templatable option in your custom_component?
What am I misunderstanding here, seems a very interesting option id love to explore

**Comment by robmarkcole** [comment]
Yes that's correct. What do you mean ' a templatable option'? I have my config [here ](https://github.com/robmarkcole/robins-homeassistant-config)if you wish to see my integration.
Cheers

**Comment by hvbhome** [comment]
"What do you mean ' a templatable option'"

i was referring to the sensors created by the Custom Component of which we can create (extract) separate sensors through templating, like in your documentation . 

About the iPhone in your group: is this the regular device_tracker or a device created trough your CC? 
I now even have my hub registered in the Meethue online interface, but still don't see it popping up...

Would help if you could describe a bit more precise what you mean by:
' if you have configured a Geofence in the Hue app'. The Term Geofence is not available there  (using App version 2 btw) . I know rules and schedules can be hand made, but I don't think you're referring to that are you?

Will investigate further. 

Cheers,
Marius

**Comment by hvbhome** [comment]
im still puzzled, though i found out you're probably talking about the App  version 1, which has in fact a geofencing setting?
Ive enabled that, logged in to it, and see the app reporting leaving and entering the home.

What i don't see however is any evidence Hassio notices too ;-) What am i to look for in the sensor too get it to show up?
Its not just my regular iPhone device-tracker is it? they are working fine, and report correctly:

![schermafbeelding 2018-02-14 om 17 32 27](https://user-images.githubusercontent.com/33354141/36215663-018cb29e-11ad-11e8-9141-6cde35b02232.jpg)

Hope you can help,
thanks,
Marius

**Comment by robmarkcole** [comment]
Hi Marius
sorry to confuse, it's not in any way a true device tracker in HA, just a regular sensor.
if it helps I'm on the iOS Hue app 2.19.0.
Check the hue API data for 
Cheers

![image](https://user-images.githubusercontent.com/11855322/36227852-4c5cd1b0-11ca-11e8-8f38-a71b2d552093.png)

![image](https://user-images.githubusercontent.com/11855322/36227944-a0552a4c-11ca-11e8-9519-1cee5958ab3f.png)

**Comment by hvbhome** [comment]
how strange, no Geofence whatsoever in my Api.... 
Also, i the App2.19.0 (same here) there's no real mentioning of Geofence is there? Only login (to MyHue) on the discover tab?

---edit----

i found it! Had to not only login, but also enable 'routines' ....
I can see the geofence now in the Api, will wait and see for it to appear in Hassio :-)

maybe for another thread, but since it is related: are we sure this is in any way secure? How can be ascertain Hue doesnt eavesdrop on all Hassio events or worse?

Cheers and many thanks for your patience!
Marius
