### ISSUE TITLE
Sensor Naming Convention

### ISSUE THREAD

**Issue by aFrankLion** [robmarkcole/Hue-sensors-HASS#48]
The sensor naming convention in parse_sml() in the file /custom_components/sensor/hue.py works well for the default naming convention of Hue sensors (e.g., Office sensor, Living room sensor) by inserting "motion" into the penultimate position in the name, e.g.:
  * "Office sensor" -> "Office motion sensor"
  * "Living room sensor" -> "Living room motion sensor"

However, user-defined sensor names can lead to inconsistent and awkward entity_id's in Home Assistant. For example, I had Hue sensors with the following custom names:
  * "Living room 1"
  * "Living room 2"
  * "Office"
  * "Dining room"

These Hue sensor names led to following entity_id's with the current Hue-sensors-HASS naming convention:
  * "Living room motion 1"
  * "Living room motion 2"
  * "Motion office"
  * "Dining motion room"

The simplest solution may be just to recommend in README.md to use the default Hue naming convention for sensors. A second possible approach is to drop the insertion of "motion" into the Hue sensor name. A third possible approach could involve parsing the current sensor names and cleverly naming them (e.g., does the name contain "sensor" or "motion" already, if so..), though this would be difficult to define to cover all possible names well.

**Comment by robmarkcole** [comment]
HI @aFrankLion thanks for your suggestion, I've updated the README. I will leave this 'issue' open so that others can make suggestions on the naming convention if they have ideas. My own thought is just to append 'hue' to the start of the sensor names, so you would get sensor.hue_Living_room_2 for example.
Cheers

**Comment by robmarkcole** [comment]
@aFrankLion I think your suggestion that `motion` is dropped from naming is a good one, and that the `entity registry` should be the way to rename sensors (never used that feature myself)

**Comment by WhistleMaster** [comment]
I had the same issue with a sensor named "Dining room" changed to "Dining motion room".

**Comment by yottatsa** [comment]
Depends on #115

**Comment by LordSata** [comment]
Can i ask if the issue is still open? I have the same problem.... But i read too late of this issue.

**Comment by robmarkcole** [comment]
Stale
