### ISSUE TITLE
No Longer Works With Hassio Version 0.66.0

### ISSUE THREAD

**Issue by ConorMatthews** [robmarkcole/Hue-sensors-HASS#52]

**Comment by JuliusLedoux** [comment]
Mine is working on version 0.66.1. I made sure to remove the previous version installed on my custom_componenets folder and also modified the hue.py file to have my key (provided by hue) on the line: 
URL = "http://192.168.1.111/api/xxxxxxxxxxxxxxxxxKeyxxxxxxxxxxxx/sensors"
Hope this helps!

**Comment by ben2011laptops** [comment]
It says that this information is in the previous HUE file. Where is this obtained from?

**Comment by raoulteeuwen** [comment]
@ben2011laptops in the HA configuration folder, so where also you configuration.yaml etc resides.

**Comment by raoulteeuwen** [comment]
@hvbhome : not change anything as long as you think is o.k. is the best way not to break anything. But than again, that probably only postpones problems, as you might encounter extra problems when you want to go from version x to version x+5. @robmarkcole has already updated his code so it works with 0.66 (thank you!). Just check the update readme of his code, which states what you need to do (read carefully ;-)).

**Comment by hvbhome** [comment]
yes, really appreciate @robmarkcole s work! I have already upgrade the hue.py in custom_components to see what gives, a lo and behold, it really works fine, even got my Geofence phone to showup ;-)

So, i don't need the upgrade for Hue. Do need it for other issues, but i fear it would break this, given @baloob's remarks I quoted above.

So, I would really appreciate some feedback from someone having upgraded to Hassio 66.1 and using hue.py CC with good results...

Cheers,
Marius

**Comment by raoulteeuwen** [comment]
I'm running 0.66.0 with @robmarkcole s updated work without a problem...

**Comment by hvbhome** [comment]
thanks @raoulteeuwen 
had the long time ago too @jongdesteven , and talked to @robmarkcole about that, it isnt necessary any longer, at least it wasn't with the previous versions of hue.py. It was there for legacy's purposes, maybe best to take it out of the documentation altogether now..

thanks for feedback!

**Comment by thundergreen** [comment]
Short feedback  as this becomes very unclear here ..u made a mistake in description.. hue.py must be in:

/hassconfigfolder/custom_components/sensor/hue.py

**Comment by hvbhome** [comment]
nope, i didnt make a mistake. 

there's admittedly been a lot of confusion about this: 2 file being necessary with the same name. before it was Hue_sensor and _sensors, later it became twice hue.py.

the CC file by the author here had to go in /config/custom_components/sensor, the other file which was apparently needed for Hassio's support for Hue in the first place had to go in /config/custom_component.

hence my question whether this is still needed now Hassio has built-in support....

**Comment by thundergreen** [comment]
OK..can't say for hassio but venv install needs mentioned path . thanks for clearing this

**Comment by robmarkcole** [comment]
I believe this issue is stale so closing
