### ISSUE TITLE
Motion sensors should be binary_sensors

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/Hue-sensors-HASS#54]
As title

**Comment by magnus919** [comment]
You might need to use templating to get this. The motion sensor is currently also returning temperature & lux (decidedly non-binary data).

**Comment by scaarup** [comment]
+1
If it's not possible, then the motion-sensor should be created separately as binary. Unfortunately I am not good enough at Python to try this out myself.

**Comment by yottatsa** [comment]
@JuliusLedoux please use 1.0+ version for it.
