### ISSUE TITLE
Automatic integration 

### ISSUE THREAD

**Issue by mf-social** [robmarkcole/Hue-sensors-HASS#57]
Currently this component requires you to manually insert the ip address and api_key in to the code. Presumably this means that it can only be used with one bridge (which is fine for me, but maybe not so good for expansive setups).

I've just been poking around the main homeassistant config and there's now a `.config_entries.json` (I think it will also cover other domains at some point).

Anywho, here's @CCOSTAN 's one (has two bridges so better example than mine) 

https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/config/.config_entries.json

I'm guessing that 'username' is the api_key (it certainly is in mine), and obviously it also contains the ips for each bridge.

Soooooooooooooo... 

How easy would it be to cycle through this json and auto generate the url(s) without end users having to manually change the code?

Aaaaaannnnnnndddddd.... 

Presuming that's achievable, plans to integrate this into the official hue component maybe? Be it still as a separate sensor platform entry, or be it as an opt-in/out key for the Hue entry, or be it just automatically on? 

Rambling thoughts of a very tired but very curious MF.

**Comment by mf-social** [comment]
Might also alleviate some* pressure from #36 as it would be adding a few definitions to the existing test script to look for the sensors.

(*probably not loads, but it's already checking connection and updates to the bridge itself)

**Comment by hvbhome** [comment]
hi @mf-social 

you are ware the latest version is setup like this:

```
sensor:
  - platform: hue
    ip_address: !secret hue_ip
    token: !secret hue_api_key
```

and not in the code any longer ? Not sure if this takes care of you're multiple Hub question, but it works very well indeed.

**Comment by mf-social** [comment]
Yeah, I'm talking about it being automatically integrated either like this:

```
sensor:
  platform: hue
```

(and it automatically getting the keys and ip addresses)

Or to not need the sensor entry at all and it be automatic when the Hue platform is added.

**Comment by hvbhome** [comment]
sure, That would be cool indeed.
However, since Hue is rather messed up in the current HA implementation, I am very glad the CC is a separate component, working as stable as it does!

**Comment by magnus919** [comment]
@mf-social suggested automatically getting keys. I don't think this is feasible; there's a manual step of having to press the button on top of the bridge first.

**Comment by mf-social** [comment]
@magnus919, your hue integration in homeassistant already has these keys in the  `.config_entries.json` file. It just needs to be extracted from there.

**Comment by yottatsa** [comment]
Done with https://github.com/robmarkcole/Hue-sensors-HASS/pull/96, it's now

    device_tracker:
      - platform: hue
    sensor:
      - platform: hue
