### ISSUE TITLE
Misleading title?

### ISSUE THREAD

**Issue by elbogi** [robmarkcole/Hue-sensors-HASS#60]
Hello and good morning from Norway.

Just a small thing I noticed when updating my hue.py. The title of this repo is "Custom component for Hue sensors in Home-Assistant <=0.68.0". You might want to remove the "<= 0.68.0" or update it to "<= 0.68.1" since it works just fine in 0.68.1 👍 :-)

**Comment by robmarkcole** [comment]
Good to know :)
