### ISSUE TITLE
Last Motion Sensor

### ISSUE THREAD

**Issue by schneekluth** [robmarkcole/Hue-sensors-HASS#61]
Please add a sensor for last motion or add an explanation how to do it in the README.

Thanks.

**Comment by hvbhome** [comment]
see https://diyfuturism.com/index.php/2017/12/15/useful-sensor-motion-last-seen-________/

**Comment by robmarkcole** [comment]
`last_updated` doesn't always == last motion? If not then `last_motion` could be added as an attribute

**Comment by raoulteeuwen** [comment]
@schneekluth is what @hvbhome shows what you intended, are you asking for a variable for every motion sensor holding the last date and time motion was detected for that motion sensor or something else :-)?

**Comment by schneekluth** [comment]
Yes, it was exactly what I was looking for. It's already set up an running. Thanks for the advice. I didn't know hassvariables.

**Comment by hvbhome** [comment]
cool.
of course you can add the `show_last_changed: true` for the sensors, customize some more, and have it show like this:

![schermafbeelding 2018-05-25 om 23 35 30](https://user-images.githubusercontent.com/33354141/40567164-84eae424-6074-11e8-9be6-3f71a88c0063.jpg)

```
    sensor.frontdoor_motion_sensor:
      show_last_changed: true
      templates:
        icon_color: >
          if (state === 'on') return 'rgb(192, 39, 30)';
          return 'rgb(54, 95, 140)';
        icon: >
          if (state === 'on') return 'mdi:run-fast';
          return 'mdi:security-home';
        _stateDisplay: >
          if (state === 'on') return 'Alert';
          return 'Clear';
      group:
        group.philips_motion_sensors:
          friendly_name: Frontdoor
```
