### ISSUE TITLE
doesn't work with 69.1

### ISSUE THREAD

**Issue by randriksen** [robmarkcole/Hue-sensors-HASS#62]
I'm not sure what the problem is, but it's very clear that it doesn't work with 69.1.
had to remove the hue.py script from custom_components to be able to get any hue lamps to show up in HA again. tried fixing the URL in the script, but that didn't change the results. So for now i'm not getting the hue sensors to show anything.

**Comment by randriksen** [comment]
i think i found the issue. they have changed lux to lx in 69.1. so all references to lux need to be changed to lx

**Comment by hvbhome** [comment]
not sure if its up to me to answer here, but just about the only thing working perfectly in the current HA Hue setup is the CC...

you might have incorrectly set it up but the lux sensors made on the motion sensors work perfectly:

![schermafbeelding 2018-05-24 om 13 56 30](https://user-images.githubusercontent.com/33354141/40484000-4f9c3a2c-5f5a-11e8-84ae-134ee91e7f97.jpg)

dont change anything in the CC, but have it setup correctly:
```

sensor:
  - platform: hue
    ip_address: !secret hue_ip
    token: !secret hue_api_key
```

and you're good to go.

**Comment by randriksen** [comment]
when i changed all references to lux to lx things started to work again for me.

**Comment by robmarkcole** [comment]
@randriksen can you submit a PR?
Cheers

**Comment by robmarkcole** [comment]
@randriksen can you try https://github.com/robmarkcole/Hue-sensors-HASS/commit/b67055e7d050f59df19f86b1337646c4c363d3a8 which fixes lx?

**Comment by hvbhome** [comment]
> when i changed all references to lux to lx things started to work again for me.

you're sure about that? Seems odd the CC would frustrate Hue implementation.

It probably was fixed by removing the hue.py out of the /custom_components folder. This hue.py that was previously necessary indeed needs to be deleted, or the native Hue component wont work, and show no lights.
Has nothing to do with the CC here, which works just fine, including the lux, which is computed on the light level data form the sensor...
Please correct me if im wrong , but also please dont change anything not necessary and working just perfectly as it is

**Comment by hvbhome** [comment]
spoke too soon i guess...
updated to .70, and tonight suddenly this shows up in the log:

```
2018-05-30 23:20:23 ERROR (MainThread) [homeassistant.components.sensor] hue: Error on device update!
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 244, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 327, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sensor/hue.py", line 231, in update
    self._hue_id]['lux']
KeyError: 'lux'
```

the silly thing is, it only effects 1 of my sensors:

![schermafbeelding 2018-05-30 om 23 48 58](https://user-images.githubusercontent.com/33354141/40749385-1eb5e458-6464-11e8-89ec-535ad3c664db.jpg)
![schermafbeelding 2018-05-30 om 23 49 10](https://user-images.githubusercontent.com/33354141/40749386-1ed27ba4-6464-11e8-8e1f-af56669953ef.jpg)

doing so, it even frustrates the temperature sensor.
Is working fine in the App though, so i know the sensor is physically in tact.

**Comment by robmarkcole** [comment]
OK lux becomes ls in https://github.com/robmarkcole/Hue-sensors-HASS/releases/tag/v0.6
Please update.
Cheers
