### ISSUE TITLE
lx key not always present

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/Hue-sensors-HASS#67]
Need to look into this, but occasionally no `lx` key was present in data object and this was causing an exception. For now am wrapping the parsing in a `try` statement

**Comment by thevic92** [comment]
hi! i have a hue motion sensor. i see that the lux sensor only update his value when the motion sensor is activate. for example in my room when the lights turn off and there isn't any movement, the lux sensor indicates that there is still light (for example a value of 9.0 lx). only when it detected some movement, it update the lux value.  this is right or in my configuration there is a error?

**Comment by yottatsa** [comment]
@thevic92 it's intended behaviour of the sensor itself. It works same way for me https://youtu.be/i_GywKcwmKQ

**Comment by yottatsa** [comment]
Should be `None` in any case now.
