### ISSUE TITLE
Support multiple hue bridges

### ISSUE THREAD

**Issue by mateuszdrab** [robmarkcole/Hue-sensors-HASS#7]
Hi.

I currently use two hue bridges in two houses each having their config files named differently, phue_1.conf and phue_2.conf. In this configuration the sensors are not detected, however, if any of the files is renamed to phue.conf, everything works fine (for the corresponding hub).

Is there a way you could implement support for multiple bridges? I suppose you'd have to iterate them and get the config file for each.

Regards
Matt

**Comment by robmarkcole** [comment]
Hi Matt 
thanks for your suggestion. Have you set up the configuration in this way yourself manually (i.e. editing the files to add _1 extension) or was this produced by the Hue component? Is there any reason why you don't just rename to phue.conf and keep your installations separate?
Cheers

**Comment by mateuszdrab** [comment]
Hey Rob

Thanks for replying.

I will indeed be splitting the home assistant install into two instances. I didn't initially want to do it because there isn't much in my other place other than the hue bulbs but now that my mum wants to add some led strips I'll just branch it off to a separate install.

The files were produced by hass but were since renamed. I've now named one of them phue.conf as the other location won't have any hue remotes soon but I wanted to make it future proof.

The set hue scene command doesnt work either in hass but I'll report that once I test the latest version of hass which is 55. I'm on 51 atm.

Regards
