### ISSUE TITLE
Button Release events 

### ISSUE THREAD

**Issue by rudders** [robmarkcole/Hue-sensors-HASS#70]
Is there any reason why you didn’t implement the release events? Would make click and hold easier to process wouldn’t it.... I’ll have a crack and PR if it works out unless you can save me the time if the idea is flawed.

**Comment by robmarkcole** [comment]
PR is welcome. I haven’t much time, but this whole component needs to be rewritten before official integration to HA.
Cheers

**Comment by rudders** [comment]
I’ve been waiting for an excuse to learn python. I’ll give it a go.  #hack

**Comment by rudders** [comment]
PR Raised for your consideration - thanks for the component by the way - whether it needs rewriting or not it works really well and is a great addition to making my HA system more user (well my wife in particular) friendly - a worthy cause.!!
