### ISSUE TITLE
No sensors after PR#71

### ISSUE THREAD

**Issue by Djelibeybi** [robmarkcole/Hue-sensors-HASS#72]
I'm a new user and I installed the latest version from the `master` branch. I kept getting `Cannot setup Hue sensors, check your config` errors. 

After adding lots of logging, I discovered that the code in #71 was the issue. Rolling that back made all the sensors appear.

**Comment by rudders** [comment]
Can you supply the logs ?

**Comment by robmarkcole** [comment]
@rudders are you happy to look into this?
@Djelibeybi I'l add a note that the last official release is the stable version
This is the problem with having not a single unit test.. :-)

**Comment by Djelibeybi** [comment]
@rudders well, there are no real logs.  :)

I just added `_LOGGER.warning("I got here")` lines until I worked out that it was `data.update()` that failed and then assumed that the last commit was the problem because no-one else was complaining and I only installed it this afternoon.

**Comment by Djelibeybi** [comment]
@robmarkcole yeah, perhaps a note not to `git clone` unless one enjoys living on the edge. :)

**Comment by robmarkcole** [comment]
Welcome to open source!
@Djelibeybi if you can put back the offending code and generate an error that would be grea

**Comment by Djelibeybi** [comment]
FYI, it failed when trying to parse this sensor:

```
	"7": {
		"state": {
			"buttonevent": null,
			"lastupdated": "none"
		},
		"swupdate": {
			"state": "noupdates",
			"lastinstall": null
		},
		"config": {
			"on": true,
			"battery": 100,
			"reachable": true,
			"pending": []
		},
		"name": "Dining Room Dimmer",
		"type": "ZLLSwitch",
		"modelid": "RWL021",
		"manufacturername": "Philips",
		"productname": "Hue dimmer switch",
		"swversion": "5.45.1.17846",
		"uniqueid": "XX:XX:XX:XX:XX:XX:e3:61-02-fc00",
		"capabilities": {
			"certified": true
		}
	},
```

The error is simply your standard `Cannot setup Hue sensors, check your config` message.

**Comment by rudders** [comment]
I can take a look but not for a long while - just hitting Friday night my TZ and have some family commitments. Seems like a odd issue considering my change was very localised.

Do you have a hue dimmer switch? 

That’s the only code that changed. 

What other hue stuff do you have?

**Comment by Djelibeybi** [comment]
I have Hue bulbs, dimmers, motion sensors. It just needs a `not null` check, now that I'm looking at it. Let me take a stab at a PR against master for you.
