### ISSUE TITLE
Invalid config for [sensor.hue]: required key not provided @ data['ip_address']

### ISSUE THREAD

**Issue by Phoenxi131178** [robmarkcole/Hue-sensors-HASS#75]
Hey Rob, thanks for your awesome Program.

I got one problem, 

2018-07-19 05:45:06 ERROR (MainThread) [homeassistant.config] Invalid config for [sensor.hue]: required key not provided @ data['ip_address']. Got None. (See ?, line ?). Please check the docs at https://home-assistant.io/components/sensor.hue/

I have this entry in the configuration file
hue:
  bridges:
    - host: 192.168.178.21
      allow_unreachable: true
      allow_hue_groups: true
      filename: phue.conf

and this in the sensor.yaml

- platform: hue
   ip_adress: 192.168.178.21
   token: omS422jryLFEHgOrF85Uune11Db7Ir0wMYtYYF-n

i checked the hole internet ;) but i can´t get that figure out :(

thanks for your support

**Comment by robmarkcole** [comment]
Check what is returned at `http://192.168.178.21/api/omS422jryLFEHgOrF85Uune11Db7Ir0wMYtYYF-n/sensors`

**Comment by Phoenxi131178** [comment]
I got the devices.
{"1":{"state":{"daylight":true,"lastupdated":"2018-07-19T04:29:00"},"config":{"on":true,"configured":true,"sunriseoffset":73,"sunsetoffset":29},"name":"Daylight","type":"Daylight","modelid":"PHDL00","manufacturername":"Philips","swversion":"1.0"},"2":{"state":{"status":0,"lastupdated":"2018-07-18T16:26:14"},"config":{"on":true,"reachable":true},"name":"XFDHueDim64Btn1000State","type":"CLIPGenericStatus","modelid":"ButtonState","manufacturername":"xfiredesigns","swversion":"1.0","uniqueid":"65779840-D8B3-4A6C-8F78-F35FC6CC","recycle":false},"3":{"state":{"status":0,"lastupdated":"2018-07-18T16:26:14"},"config":{"on":true,"reachable":true},"name":"XFDHueDim64Btn4000State","type":"CLIPGenericStatus","modelid":"ButtonState","manufacturername":"xfiredesigns","swversion":"1.0","uniqueid":"B6D9915E-69CC-4C04-874C-8A8BE010","recycle":false},"4":{"state":{"status":0,"lastupdated":"2018-07-19T06:24:13"},"config":{"on":true,"reachable":true},"name":"Motion Sensor 49 Activity State","type":"CLIPGenericStatus","modelid":"MotionSensorState","manufacturername":"xfiredesigns","swversion":"1.0","uniqueid":"2E54F8EF-CDC7-4C85-BB3B-21E4A801","recycle":false},"5":{"state":{"status":1,"lastupdated":"2018-07-18T22:06:05"},"config":{"on":true,"reachable":true},"name":"XFDHueDim63Btn1000State","type":"CLIPGenericStatus","modelid":"ButtonState","manufacturername":"xfiredesigns","swversion":"1.0","uniqueid":"B1048890-62E6-4D97-A7ED-1A3E7020","recycle":false},"6":{"state":{"status":0,"lastupdated":"2018-07-19T03:35:44"},"config":{"on":true,"reachable":true},"name":"XFDani[2]sn:state","type":"CLIPGenericStatus","modelid":"AnimationSensor","manufacturername":"xfiredesigns","swversion":"1.0","uniqueid":"XFDani[2]sn:state","recycle":false},"7":{"state":{"status":0,"lastupdated":"none"},"config":{"on":true,"reachable":true},"name":"MotionSensor 5.Companion","type":"CLIPGenericStatus","modelid":"PHA_STATE","manufacturername":"Philips","swversion":"1.0","uniqueid":"MotionSensor 5.Companion","recycle":true},"8":{"state":{"status":0,"lastupdated":"2018-07-14T21:10:44"},"config":{"on":true,"reachable":true},"name":"XFDani[2][1]sn:step","type":"CLIPGenericStatus","modelid":"AnimationSensor","manufacturername":"xfiredesigns","swversion":"1.0","uniqueid":"XFDani[2][1]sn:step","recycle":false},"17":{"state":{"status":0,"lastupdated":"none"},"config":{"on":true,"reachable":true},"name":"MotionSensor 15.Companion","type":"CLIPGenericStatus","modelid":"PHA_STATE","manufacturername":"Philips","swversion":"1.0","uniqueid":"MotionSensor 15.Companion","recycle":true},"22":{"state":{"presence":false,"lastupdated":"none"},"config":{"on":true,"reachable":true},"name":"HomeAway","type":"CLIPPresence","modelid":"HOMEAWAY","manufacturername":"Philips","swversion":"A_1","uniqueid":"L_01_R9jei","recycle":false},"27":{"state":{"presence":false,"lastupdated":"none"},"config":{"on":true,"reachable":true},"name":"Jans iPhone","type":"Geofence","modelid":"HA_GEOFENCE","manufacturername":"Philips","swversion":"A_1","uniqueid":"L_02_jpv9L","recycle":false},"40":{"state":{"status":0,"lastupdated":"none"},"config":{"on":true,"reachable":true},"name":"start - stop","type":"CLIPGenericStatus","modelid":"HUELABSVDIMMER","manufacturername":"Philips","swversion":"1.0","uniqueid":"40fb-35a5-4654-82a3","recycle":true},"41":{"state":{"status":0,"lastupdated":"none"},"config":{"on":true,"reachable":true},"name":"state","type":"CLIPGenericStatus","modelid":"HUELABSSTOGGLE","manufacturername":"Philips","swversion":"1.0","uniqueid":"2:0:2bb4-b467-45c8-9546","recycle":true},"46":{"state":{"presence":false,"lastupdated":"2018-07-19T02:39:06"},"config":{"on":true,"reachable":true},"name":"Jan","type":"CLIPPresence","modelid":"XFDPresence","manufacturername":"xfiredesigns","swversion":"1.0","uniqueid":"F726D4E7-FACC-4240-A748-5C3D3ED9","recycle":false},"47":{"state":{"presence":true,"lastupdated":"2018-07-18T14:25:08"},"config":{"on":true,"reachable":true},"name":"XFDAnybodyHome","type":"CLIPPresence","modelid":"XFDPresence","manufacturername":"xfiredesigns","swversion":"1.0","uniqueid":"517B11AA-D15C-42DC-AAEB-9E36FF81","recycle":false},"48":{"state":{"temperature":2195,"lastupdated":"2018-07-19T06:27:26"},"swupdate":{"state":"noupdates","lastinstall":null},"config":{"on":true,"battery":94,"reachable":true,"alert":"none","ledindication":false,"usertest":false,"pending":[]},"name":"Flur Bewegungsmelder Temp","type":"ZLLTemperature","modelid":"SML001","manufacturername":"Philips","productname":"Hue temperature sensor","swversion":"6.1.0.18912","uniqueid":"00:17:88:01:02:02:29:45-02-0402","capabilities":{"certified":true}},"49":{"state":{"presence":false,"lastupdated":"2018-07-19T06:23:28"},"swupdate":{"state":"noupdates","lastinstall":null},"config":{"on":true,"battery":94,"reachable":true,"alert":"none","ledindication":false,"usertest":false,"sensitivity":0,"sensitivitymax":2,"pending":[]},"name":"Flur Bewegungsmelder","type":"ZLLPresence","modelid":"SML001","manufacturername":"Philips","productname":"Hue motion sensor","swversion":"6.1.0.18912","uniqueid":"00:17:88:01:02:02:29:45-02-0406","capabilities":{"certified":true}},"50":{"state":{"lightlevel":13945,"dark":true,"daylight":false,"lastupdated":"2018-07-19T06:29:15"},"swupdate":{"state":"noupdates","lastinstall":null},"config":{"on":true,"battery":94,"reachable":true,"alert":"none","tholddark":16000,"tholdoffset":7000,"ledindication":false,"usertest":false,"pending":[]},"name":"Flur Bewegungsmelder Light","type":"ZLLLightLevel","modelid":"SML001","manufacturername":"Philips","productname":"Hue ambient light sensor","swversion":"6.1.0.18912","uniqueid":"00:17:88:01:02:02:29:45-02-0400","capabilities":{"certified":true}},"52":{"state":{"temperature":2135,"lastupdated":"2018-07-19T06:28:21"},"swupdate":{"state":"noupdates","lastinstall":null},"config":{"on":true,"battery":96,"reachable":true,"alert":"none","ledindication":false,"usertest":false,"pending":[]},"name":"Schlafzimmer Bewegungsmelder Tem","type":"ZLLTemperature","modelid":"SML001","manufacturername":"Philips","productname":"Hue temperature sensor","swversion":"6.1.0.18912","uniqueid":"00:17:88:01:02:01:00:5e-02-0402","capabilities":{"certified":true}},"53":{"state":{"presence":false,"lastupdated":"2018-07-19T06:28:39"},"swupdate":{"state":"noupdates","lastinstall":null},"config":{"on":true,"battery":96,"reachable":true,"alert":"none","ledindication":false,"usertest":false,"sensitivity":0,"sensitivitymax":2,"pending":[]},"name":"Schlafzimmer Bewegungsmelder","type":"ZLLPresence","modelid":"SML001","manufacturername":"Philips","productname":"Hue motion sensor","swversion":"6.1.0.18912","uniqueid":"00:17:88:01:02:01:00:5e-02-0406","capabilities":{"certified":true}},"54":{"state":{"lightlevel":17715,"dark":false,"daylight":false,"lastupdated":"2018-07-19T06:28:29"},"swupdate":{"state":"noupdates","lastinstall":null},"config":{"on":true,"battery":96,"reachable":true,"alert":"none","tholddark":16000,"tholdoffset":7000,"ledindication":false,"usertest":false,"pending":[]},"name":"Schlafzimmer Bewegungsmelder Lig","type":"ZLLLightLevel","modelid":"SML001","manufacturername":"Philips","productname":"Hue ambient light sensor","swversion":"6.1.0.18912","uniqueid":"00:17:88:01:02:01:00:5e-02-0400","capabilities":{"certified":true}},"55":{"state":{"buttonevent":4002,"lastupdated":"2018-07-16T20:30:08"},"swupdate":{"state":"noupdates","lastinstall":null},"config":{"on":true,"battery":100,"reachable":true,"pending":[]},"name":"Flur Schalter","type":"ZLLSwitch","modelid":"RWL021","manufacturername":"Philips","productname":"Hue dimmer switch","swversion":"5.45.1.17846","uniqueid":"00:17:88:01:04:f6:90:3c-02-fc00","capabilities":{"certified":true}},"58":{"state":{"status":0,"lastupdated":"2018-07-16T20:30:18"},"config":{"on":true,"reachable":true},"name":"XFDHueDim55Btn1000State","type":"CLIPGenericStatus","modelid":"ButtonState","manufacturername":"xfiredesigns","swversion":"1.0","uniqueid":"86D1C9B7-2C22-49F2-8C00-854D1759","recycle":false},"60":{"state":{"buttonevent":4002,"lastupdated":"2018-07-19T02:38:35"},"swupdate":{"state":"noupdates","lastinstall":null},"config":{"on":true,"battery":100,"reachable":true,"pending":[]},"name":"Kinderzimmer Schalter","type":"ZLLSwitch","modelid":"RWL021","manufacturername":"Philips","productname":"Hue dimmer switch","swversion":"5.45.1.17846","uniqueid":"00:17:88:01:02:0d:69:65-02-fc00","capabilities":{"certified":true}},"61":{"state":{"status":0,"lastupdated":"2018-07-19T02:38:45"},"config":{"on":true,"reachable":true},"name":"XFDHueDim60Btn1000State","type":"CLIPGenericStatus","modelid":"ButtonState","manufacturername":"xfiredesigns","swversion":"1.0","uniqueid":"46FC2CBC-EE1D-4EE2-957B-0391848A","recycle":false},"62":{"state":{"presence":true,"lastupdated":"2018-07-18T07:25:10"},"config":{"on":true,"reachable":true},"name":"Ulrike","type":"CLIPPresence","modelid":"XFDPresence","manufacturername":"xfiredesigns","swversion":"1.0","uniqueid":"F20E8E82-5042-48CB-8A61-2A6A0BF4","recycle":false},"63":{"state":{"buttonevent":4002,"lastupdated":"2018-07-19T03:35:44"},"swupdate":{"state":"noupdates","lastinstall":null},"config":{"on":true,"battery":100,"reachable":true,"pending":[]},"name":"Schlafzimmer Schalter Ulli","type":"ZLLSwitch","modelid":"RWL021","manufacturername":"Philips","productname":"Hue dimmer switch","swversion":"5.45.1.16265","uniqueid":"00:17:88:01:10:32:36:c0-02-fc00","capabilities":{"certified":true}},"64":{"state":{"buttonevent":4002,"lastupdated":"2018-07-18T16:26:04"},"swupdate":{"state":"noupdates","lastinstall":null},"config":{"on":true,"battery":100,"reachable":true,"pending":[]},"name":"Schlafzimmer Schalter Jan","type":"ZLLSwitch","modelid":"RWL021","manufacturername":"Philips","productname":"Hue dimmer switch","swversion":"5.45.1.16265","uniqueid":"00:17:88:01:10:32:36:bf-02-fc00","capabilities":{"certified":true}}}

**Comment by robmarkcole** [comment]
OK you've probably just got some dodgy whitespace in your config. Yaml sucks.

**Comment by Phoenxi131178** [comment]
ok thanks i will check this

**Comment by raoulteeuwen** [comment]
Just noticed your YAML has "ip_adress", mine has "ip_address", so double d > might that be the problem?
