### ISSUE TITLE
Unable to get it workin

### ISSUE THREAD

**Issue by thomasraabo** [robmarkcole/Hue-sensors-HASS#83]
When starting

Config directory: /home/homeassistant/.homeassistant
2018-08-22 23:20:56 ERROR (SyncWorker_0) [homeassistant.util.yaml] while parsing a block collection
  in "/home/homeassistant/.homeassistant/configuration.yaml", line 61, column 3
expected <block end>, but found '?'
  in "/home/homeassistant/.homeassistant/configuration.yaml", line 62, column 3
2018-08-22 23:20:56 ERROR (MainThread) [homeassistant.bootstrap] Error loading /home/homeassistant/.homeassistant/configuration.yaml: while parsing a block collection
  in "/home/homeassistant/.homeassistant/configuration.yaml", line 61, column 3
expected <block end>, but found '?'
  in "/home/homeassistant/.homeassistant/configuration.yaml", line 62, column 3

my config
sensor:
  - platform: hue
  ip_address: 192.168.1.122
  token: XXXX

and my directory stucture

e:/home/homeassistant/.homeassistant# ls
automations.yaml    custom_components  deps                  groups.yaml         home-assistant_v2.db  OZW_Log.txt   scripts.yaml  tts                   zwscene.xml
configuration.yaml  customize.yaml     entity_registry.yaml  home-assistant.log  options.xml           pyozw.sqlite  secrets.yaml  zwcfg_0xd1d82

**Comment by raoulteeuwen** [comment]
Can you share your configuration.yaml (using the <> symbol in the editor on this webpage to format the code properly)? Remove any passwords if they're not stored in a seperate secret.yaml.

**Comment by thomasraabo** [comment]
Here you go

https://pastebin.com/dqktNXbL

**Comment by disrupted** [comment]
indentation looks off

**Comment by thomasraabo** [comment]
on the sensor part?
sensor:
 - platform: hue
 ip_address: '192.168.1.122'
 token: 

?

**Comment by pve84** [comment]
You have the sensor component twice in you configuration and the indentation is indeed off like @disrupted mentioned.
from line 57 to 64 should look like this
```
sensor:
  - platform: yr
  - platform: hue
     ip_address: 192.168.1.122
     token: 
 ```
Indentation is very important when working with yaml files

**Comment by disrupted** [comment]
here is another small mistake with indentation.
try this:
```yaml
sensor:
  - platform: yr
  - platform: hue
    ip_address: 192.168.1.122
    token: XXXX
```

**Comment by robmarkcole** [comment]
Please try 1.0
