### ISSUE TITLE
Problems getting it working

### ISSUE THREAD

**Issue by hookbeak** [robmarkcole/Hue-sensors-HASS#87]
Hi guys, hope you can help me with this - please bear in mind i'm a *very* new user to HA and find it generally baffling.

I have the component all installed - no errors showing. However if i add the following to groups.yaml

default_view:
  view: yes
  entities:
    - group.Hue

Hue:
entities: 
- sensor.ThomasDimmer

( note: that's a - not a bullet, the editor keeps converting it... )

Then my overview screen is blank. If i clear the groups.yaml, all my lights and switches come back.

Any ideas? No errors show at any point in the log....

**Comment by robmarkcole** [comment]
This isn't due to the component, please enquire on the forums as likely HA config issue
