### ISSUE TITLE
Cannot set state manually

### ISSUE THREAD

**Issue by Aephir** [robmarkcole/Hue-sensors-HASS#88]
First, thanks for the work put into this!

My issue is kind of related to #85 .

I am using a few remotes, and especially for the Hue Tap, I need a idle state (this one only has `1_click`, not `1_click_up`, `1_click_hold`, etc.). Otherwise it cannot see sequential clicks of the same button. I
 made either a shell_command or a python script to change the state to "idle" after running an automation.

e.g.:
```
hass.states.set('sensor.bedroom_switch', 'idle')
```

But when I run this, I can see in the dev-states the state change to "idle" for less than a second, before it automatically changes back to whatever the previous state was. I'm not sure why, and if this is because of the way this component was written, but it doesn't happen when I try the same for other sensors. So if it is something that could be addressed, it would be greatly appreciated.

I can't offer to help with the code (I'm absolutely clueless), but if I can help with testing, I'd be happy to.

**Comment by robmarkcole** [comment]
These remotes need to be implemented as remotes really

**Comment by Aephir** [comment]
Is that something I can do while setting up, or something that should/could be done in the component code?

In any case, I broke my hue tap. But before doing that, I made a python script in appdaemon to control it, and there it did react to multiple clicks of the same button. So I think I have a workaround. Now I just need to get a new remote 🙄

**Comment by yottatsa** [comment]
With 1.0.2 sensors will be updated only when the bridge state changes, so you could potentially set the state.

**Comment by yottatsa** [comment]
Duplicate: #85
