### ISSUE TITLE
how is this different from https://github.com/home-assistant/home-assistant/pull/15121 ?

### ISSUE THREAD

**Issue by maxandersen** [robmarkcole/Hue-sensors-HASS#89]
...and which one would it make sense to try get into default hass ?

**Comment by jjanderson** [comment]
Would also like to know as I have a feeling the latest template sensor changes have broken my coniguration.

**Comment by jjanderson** [comment]
Looks like the one you reference has gone stale and never made it in....

**Comment by maxandersen** [comment]
Yes, but so does this one :) the Pr makes it part of hue platform where a this is external to it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jjanderson** [comment]
yes, but there is loads of stuff in HA that never makes it into the official stack but just works.... This one is working fine for me atm... if it ain't broke.... don't fix it... :-)

Besides, I refer hacks than the official 3rd party stuff.... You can't even control or read temp in the official hue app.... go figure

**Comment by maxandersen** [comment]
sure - but since this makes hue much more useful and atm you need to do double setup i would much rather prefer this became part of has so those using hue don't have to be tweaking/guessing their way through making this work.

**Comment by jjanderson** [comment]
well, to be honest, this s probably the best answer... https://community.home-assistant.io/t/zigbee2mqtt-getting-rid-of-your-proprietary-zigbee-bridges-xiaomi-hue-tradfri/52108

**Comment by maxandersen** [comment]
yeah, I eventually ended up getting a conbee stick so now i'm free from the limitations of hue official bridge ;)
