### ISSUE TITLE
Stops updating after a few hours

### ISSUE THREAD

**Issue by mf-social** [robmarkcole/Hue-sensors-HASS#90]
Hi,

For the last couple of weeks I've been having a problem with this component suddenly stopping updating.  There doesn't seem to be any rhyme or reason to it, and the only thing in the logs is the expected 'updating sensor took longer than x seconds'.

For example none of my sensors have updated since 21.37 last night.  I have no idea why and there is nothing specific in the log around that time, it's like it's just stopped bothering.

If I restart HA it will work fine for a while (maybe a couple of hours, maybe a day or so) but definitely by this time Saturday I'll be in the same boat and somewhere between now and then the updates will suddenly stop.

Any idea how I can try to diagnose this?

**Comment by littlefeltfangs** [comment]
I had this problem when I was running in a windows docker. I've not had it
since switching to a pi/hass.io setup. I never did manage to diagnose what
was causing the problem for me, but it also took out my Tado sensors at the
same time, so my guess was something outside the Hue-sensors-HASS component
(and possibly something to do with how docker was handling the network
interface).

No idea if that has any relevance to your setup, I share your frustration.

**Comment by mf-social** [comment]
No, I'm in a venv on debian here. It's been working fine for ages and nothing has changed on my network AFAIK.

I also have a rest switch that turns on/off one of the sensors (for the bathroom, so it doesn't turn the light off if you're in the bath) and that's working fine, and of course 'normal' hue control via homeassistant is OK so I don't think it's a connectivity problem.

Is there any way I can 'see' the process? Like component sends message to hue hub, this was the message it sent, received a reply, this was the reply it got, updated homeassistant with the information? Maybe if I can pin down which bit of the process is borked I can get to the bottom of it.

**Comment by robmarkcole** [comment]
You could insert a few `_LOGGER.debug(something)` to help diagnose

**Comment by yottatsa** [comment]
There is `_LOGGER.debug` in 1.0.1. Please update and enable logging with

    logger: 
      logs:
        custom_components.sensor.hue: debug

Then you should see 

    DEBUG (MainThread) [custom_components.sensor.hue] hue_api_response {...

**Comment by robmarkcole** [comment]
Been quiet for a while, closing
