### ISSUE TITLE
Why is this so complicated?

### ISSUE THREAD

**Issue by EpicLPer** [robmarkcole/Hue-sensors-HASS#94]
I know this might be a "weird" issue to open but... why is this so difficult to set up? Why do we have to create a developer account etc. just to get the status of a simple sensor?

There's an app for Windows called "hueDynamic" which, after simply pressing the button on the bridge to connect it to the app, will allow you to configure the 4 button remote with commands (within the limitation of the Hue Bridge of course), see the status of the motion sensors incl. temperature and so on.
![image](https://user-images.githubusercontent.com/8442196/50543116-2006dd00-0bce-11e9-8f7d-dcc5bd822681.png)
![image](https://user-images.githubusercontent.com/8442196/50543118-26955480-0bce-11e9-98d8-5ec1a205ddec.png)

So my question is: Why is creating a developer key necessary when a normal app can just do it? Can't you get all the necessary infos out of the JSON files the bridge provides already anyways?

**Comment by robmarkcole** [comment]
Please try 1.0
