### ISSUE TITLE
How about submitting your work to the default repo... ?!?

### ISSUE THREAD

**Issue by bk1285** [robmarkcole/Hue-sensors-HASS#97]
Hi @robmarkcole,

I just added your implementation to my HASS installation and like it a lot. Did you consider to add it to the default home assistant project?

... in other words: the issue I'd like to report is the need of a custom installation to make use of your work... ;)

Best,
Bernd

**Comment by robmarkcole** [comment]
HI @bk1285 
please see https://community.home-assistant.io/t/official-hue-sensors-component/76342/8
Thanks
