### ISSUE TITLE
Error setting up component

### ISSUE THREAD

**Issue by sti0** [robmarkcole/Hue-sensors-HASS#99]
I recently updated to 1.0, now I got the following error on setting up the component:
```
2018-12-31 11:59:37 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform hue
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/config/custom_components/sensor/hue.py", line 150, in async_setup_platform
    for key in data.data.keys():
AttributeError: 'NoneType' object has no attribute 'keys'

```
configuration.yaml:
```
 sensor:
  - platform: hue

```

Rolling back to 0.8.

**Comment by WhistleMaster** [comment]
Same here

**Comment by robmarkcole** [comment]
Hard to debug with such limited info. Whats your setup? Multiple bridges?

**Comment by sti0** [comment]
I'm running hass.io 0.84.6 on a raspberry pi and one hue bridge 2.0 with latest firmware in a wired network.

Please let me know if you need more information (and which one). Thanks.

**Comment by WhistleMaster** [comment]
HA 0.84.6 with Docker with a single hue bridge (v2).

**Comment by raoulteeuwen** [comment]
Fyi, just informing it 'can' work: i'm on 0.84.6 on an Rpi3b and 1 v2 bridge, and running 1.0 with no problem.

**Comment by Mariusthvdb** [comment]
what would be the advantage upgrading to 1.0? other than the device-tracker being new to the setup?

**Comment by Mariusthvdb** [comment]
one more thing:
the new Hue device_tracker creates the same device_tracker entity as the existing iCloud device_tracker. Maybe give it an extra hue identification would be best? device_tracker.hue_name?

**Comment by yottatsa** [comment]
@Mariusthvdb it's migrated to Hue platform, so it requires no setup, and relies on `aiohue`.

**Comment by yottatsa** [comment]
@sti0 @WhistleMaster please enable debug logging for the component and restart the home assistant.

    logger: 
      logs:
        custom_components.sensor.hue: debug

There should be a line like

    DEBUG (MainThread) [custom_components.sensor.hue] hue_api_response {...
